/* Het land dat je bij je gegevens instelt.
 *
 * Het staat NIET op je profiel: niemand hoeft te zien waar je woont. Het is een
 * instelling met twee gevolgen: de advertenties worden er persoonlijker van, en
 * de draaiknop van jouw land gaat open om met COINS te kopen in plaats van met
 * cash. Alle andere landenknoppen blijven cash.
 *
 * De codes zijn de tweeletterige ISO-codes, want dat is wat de server opslaat.
 * De vlagplaatjes komen later; tot die tijd is de naam het merkteken. */

export type Land = { code: string; naam: string };

/* Welke draaiknop bij welk land hoort. Dezelfde tabel staat in db.py, want de
 * server moet de aankoop kunnen keuren en mag een cliënt niet geloven. */
export const LAND_BUZZERS: Record<string, string> = {
  NL: "bz01", IT: "bz02", SR: "bz03", JM: "bz04", BR: "bz05",
  ES: "bz13", CW: "bz14", DE: "bz15", BE: "bz16", FR: "bz17",
};

/* Nederland staat bovenaan omdat de app daar begon en het de standaard is; de
 * rest loopt alfabetisch, zodat zoeken en scrollen allebei werken. */
export const LANDEN: Land[] = [
  { code: "NL", naam: "Nederland" },
  { code: "AF", naam: "Afghanistan" },
  { code: "AL", naam: "Albanië" },
  { code: "DZ", naam: "Algerije" },
  { code: "AO", naam: "Angola" },
  { code: "AR", naam: "Argentinië" },
  { code: "AM", naam: "Armenië" },
  { code: "AW", naam: "Aruba" },
  { code: "AU", naam: "Australië" },
  { code: "AZ", naam: "Azerbeidzjan" },
  { code: "BS", naam: "Bahama's" },
  { code: "BD", naam: "Bangladesh" },
  { code: "BB", naam: "Barbados" },
  { code: "BE", naam: "België" },
  { code: "BZ", naam: "Belize" },
  { code: "BJ", naam: "Benin" },
  { code: "BO", naam: "Bolivia" },
  { code: "BA", naam: "Bosnië en Herzegovina" },
  { code: "BW", naam: "Botswana" },
  { code: "BR", naam: "Brazilië" },
  { code: "BG", naam: "Bulgarije" },
  { code: "BF", naam: "Burkina Faso" },
  { code: "BI", naam: "Burundi" },
  { code: "KH", naam: "Cambodja" },
  { code: "CA", naam: "Canada" },
  { code: "CF", naam: "Centraal-Afrikaanse Republiek" },
  { code: "CL", naam: "Chili" },
  { code: "CN", naam: "China" },
  { code: "CO", naam: "Colombia" },
  { code: "CR", naam: "Costa Rica" },
  { code: "CU", naam: "Cuba" },
  { code: "CW", naam: "Curaçao" },
  { code: "CY", naam: "Cyprus" },
  { code: "DK", naam: "Denemarken" },
  { code: "DE", naam: "Duitsland" },
  { code: "EC", naam: "Ecuador" },
  { code: "EG", naam: "Egypte" },
  { code: "SV", naam: "El Salvador" },
  { code: "ER", naam: "Eritrea" },
  { code: "EE", naam: "Estland" },
  { code: "ET", naam: "Ethiopië" },
  { code: "PH", naam: "Filipijnen" },
  { code: "FI", naam: "Finland" },
  { code: "FR", naam: "Frankrijk" },
  { code: "GA", naam: "Gabon" },
  { code: "GM", naam: "Gambia" },
  { code: "GE", naam: "Georgië" },
  { code: "GH", naam: "Ghana" },
  { code: "GD", naam: "Grenada" },
  { code: "GR", naam: "Griekenland" },
  { code: "GT", naam: "Guatemala" },
  { code: "GN", naam: "Guinee" },
  { code: "GY", naam: "Guyana" },
  { code: "HT", naam: "Haïti" },
  { code: "HN", naam: "Honduras" },
  { code: "HU", naam: "Hongarije" },
  { code: "IE", naam: "Ierland" },
  { code: "IS", naam: "IJsland" },
  { code: "IN", naam: "India" },
  { code: "ID", naam: "Indonesië" },
  { code: "IQ", naam: "Irak" },
  { code: "IR", naam: "Iran" },
  { code: "IL", naam: "Israël" },
  { code: "IT", naam: "Italië" },
  { code: "CI", naam: "Ivoorkust" },
  { code: "JM", naam: "Jamaica" },
  { code: "JP", naam: "Japan" },
  { code: "YE", naam: "Jemen" },
  { code: "JO", naam: "Jordanië" },
  { code: "CV", naam: "Kaapverdië" },
  { code: "CM", naam: "Kameroen" },
  { code: "KZ", naam: "Kazachstan" },
  { code: "KE", naam: "Kenia" },
  { code: "KG", naam: "Kirgizië" },
  { code: "KW", naam: "Koeweit" },
  { code: "HR", naam: "Kroatië" },
  { code: "LA", naam: "Laos" },
  { code: "LV", naam: "Letland" },
  { code: "LB", naam: "Libanon" },
  { code: "LR", naam: "Liberia" },
  { code: "LY", naam: "Libië" },
  { code: "LT", naam: "Litouwen" },
  { code: "LU", naam: "Luxemburg" },
  { code: "MG", naam: "Madagaskar" },
  { code: "MW", naam: "Malawi" },
  { code: "MY", naam: "Maleisië" },
  { code: "ML", naam: "Mali" },
  { code: "MT", naam: "Malta" },
  { code: "MA", naam: "Marokko" },
  { code: "MR", naam: "Mauritanië" },
  { code: "MU", naam: "Mauritius" },
  { code: "MX", naam: "Mexico" },
  { code: "MD", naam: "Moldavië" },
  { code: "MN", naam: "Mongolië" },
  { code: "ME", naam: "Montenegro" },
  { code: "MZ", naam: "Mozambique" },
  { code: "MM", naam: "Myanmar" },
  { code: "NA", naam: "Namibië" },
  { code: "NP", naam: "Nepal" },
  { code: "NI", naam: "Nicaragua" },
  { code: "NZ", naam: "Nieuw-Zeeland" },
  { code: "NE", naam: "Niger" },
  { code: "NG", naam: "Nigeria" },
  { code: "KP", naam: "Noord-Korea" },
  { code: "MK", naam: "Noord-Macedonië" },
  { code: "NO", naam: "Noorwegen" },
  { code: "UA", naam: "Oekraïne" },
  { code: "UG", naam: "Oeganda" },
  { code: "UZ", naam: "Oezbekistan" },
  { code: "OM", naam: "Oman" },
  { code: "AT", naam: "Oostenrijk" },
  { code: "PK", naam: "Pakistan" },
  { code: "PA", naam: "Panama" },
  { code: "PY", naam: "Paraguay" },
  { code: "PE", naam: "Peru" },
  { code: "PL", naam: "Polen" },
  { code: "PT", naam: "Portugal" },
  { code: "PR", naam: "Puerto Rico" },
  { code: "QA", naam: "Qatar" },
  { code: "RO", naam: "Roemenië" },
  { code: "RU", naam: "Rusland" },
  { code: "RW", naam: "Rwanda" },
  { code: "KN", naam: "Saint Kitts en Nevis" },
  { code: "LC", naam: "Saint Lucia" },
  { code: "SA", naam: "Saoedi-Arabië" },
  { code: "SN", naam: "Senegal" },
  { code: "RS", naam: "Servië" },
  { code: "SL", naam: "Sierra Leone" },
  { code: "SG", naam: "Singapore" },
  { code: "SI", naam: "Slovenië" },
  { code: "SK", naam: "Slowakije" },
  { code: "SD", naam: "Soedan" },
  { code: "SO", naam: "Somalië" },
  { code: "ES", naam: "Spanje" },
  { code: "LK", naam: "Sri Lanka" },
  { code: "SR", naam: "Suriname" },
  { code: "SY", naam: "Syrië" },
  { code: "TJ", naam: "Tadzjikistan" },
  { code: "TZ", naam: "Tanzania" },
  { code: "TH", naam: "Thailand" },
  { code: "TG", naam: "Togo" },
  { code: "TT", naam: "Trinidad en Tobago" },
  { code: "TD", naam: "Tsjaad" },
  { code: "CZ", naam: "Tsjechië" },
  { code: "TN", naam: "Tunesië" },
  { code: "TR", naam: "Turkije" },
  { code: "UY", naam: "Uruguay" },
  { code: "VE", naam: "Venezuela" },
  { code: "AE", naam: "Verenigde Arabische Emiraten" },
  { code: "US", naam: "Verenigde Staten" },
  { code: "GB", naam: "Verenigd Koninkrijk" },
  { code: "VN", naam: "Vietnam" },
  { code: "BY", naam: "Wit-Rusland" },
  { code: "ZM", naam: "Zambia" },
  { code: "ZW", naam: "Zimbabwe" },
  { code: "ZA", naam: "Zuid-Afrika" },
  { code: "KR", naam: "Zuid-Korea" },
  { code: "SS", naam: "Zuid-Soedan" },
  { code: "SE", naam: "Zweden" },
  { code: "CH", naam: "Zwitserland" },
];

export function landNaam(code: string | null | undefined): string {
  const c = (code || "NL").toUpperCase();
  return LANDEN.find((l) => l.code === c)?.naam ?? c;
}

/* De draaiknop die voor JOU met coins te koop is. null als er voor jouw land
 * (nog) geen knop bestaat. */
export function landBuzzer(code: string | null | undefined): string | null {
  return LAND_BUZZERS[(code || "NL").toUpperCase()] ?? null;
}
