"""Pen Neer — persistence layer (SQLite, stdlib sqlite3).

Everything account-related lives here: users, device tokens, magic-link login
codes, friendships, blocks, room invites, game history and badges. Rooms stay
in-memory (RoomManager); this database only holds what must survive a restart.

Single-process server, tiny queries: sync sqlite3 behind one lock is plenty.
WAL mode keeps readers and the writer out of each other's way. The DB path
comes from PENNEER_DB_PATH (prod: a Coolify persistent volume, e.g.
/data/penneer.db) and falls back to ./penneer.db for local dev.
"""
from __future__ import annotations

import hashlib
import os
import re
import secrets
import sqlite3
import threading
import time
from typing import Any, Optional

DB_PATH = os.environ.get("PENNEER_DB_PATH", "penneer.db")

NAME_RE = re.compile(r"^[A-Za-z0-9À-ÿ_\- ]{2,20}$")
# Small blunt blocklist for public profile names (substring match, lowercase).
NAME_BLOCKLIST = ("hitler", "nazi", "kanker", "neger", "faggot")

TOKEN_BYTES = 24
LOGIN_CODE_TTL = 15 * 60          # magic link valid for 15 minutes
INVITE_TTL = 60 * 60              # room invites expire after an hour
AVATAR_MAX_BYTES = 300_000        # client resizes to ~256px JPEG; hard cap here

_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    name_lower TEXT NOT NULL UNIQUE,
    email TEXT UNIQUE,
    avatar BLOB,
    avatar_mime TEXT,
    avatar_ver INTEGER NOT NULL DEFAULT 0,
    color TEXT NOT NULL DEFAULT '#FFC23D',
    ai_unlocked INTEGER NOT NULL DEFAULT 0,   -- AI referee bought for this account
    created_at REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS tokens (
    token_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at REAL NOT NULL,
    last_seen REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS login_codes (
    code_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at REAL NOT NULL,
    used INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS friends (
    a TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    b TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status TEXT NOT NULL,             -- pending | accepted
    requested_by TEXT NOT NULL,
    created_at REAL NOT NULL,
    PRIMARY KEY (a, b)                -- canonical: a < b
);
CREATE TABLE IF NOT EXISTS blocks (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at REAL NOT NULL,
    PRIMARY KEY (user_id, blocked_id)
);
CREATE TABLE IF NOT EXISTS invites (
    id TEXT PRIMARY KEY,
    from_user TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    to_user TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    room_code TEXT NOT NULL,
    kind TEXT NOT NULL,               -- invite | challenge
    status TEXT NOT NULL DEFAULT 'pending',  -- pending | accepted | declined
    created_at REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS games (
    id TEXT PRIMARY KEY,
    room_code TEXT NOT NULL,
    finished_at REAL NOT NULL,
    rounds INTEGER NOT NULL,
    lenient INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS game_players (
    game_id TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    is_winner INTEGER NOT NULL,
    uniques INTEGER NOT NULL DEFAULT 0,
    dubbels INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (game_id, user_id)
);
CREATE TABLE IF NOT EXISTS badges (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    badge TEXT NOT NULL,
    earned_at REAL NOT NULL,
    PRIMARY KEY (user_id, badge)
);
-- Shop: one-time codes that unlock the AI referee for ONE account (never admin).
-- Generated by the owner (source 'admin') or minted on a paid PayPal order
-- (source 'paypal'). Only the hash is stored; the plain code is shown once.
CREATE TABLE IF NOT EXISTS ai_codes (
    code_hash TEXT PRIMARY KEY,
    source TEXT NOT NULL,              -- admin | paypal
    product TEXT NOT NULL DEFAULT 'ai', -- ai | avatars (what the code unlocks)
    created_at REAL NOT NULL,
    redeemed_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    redeemed_at REAL
);
-- PayPal purchases, keyed by the PayPal order id so a capture is idempotent
-- (a ret/replayed capture returns the same already-issued code, never a second).
CREATE TABLE IF NOT EXISTS purchases (
    order_id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    product TEXT NOT NULL DEFAULT 'ai', -- ai | avatars
    user_id TEXT,
    amount TEXT,
    currency TEXT,
    code TEXT,                         -- the ai_code plain value issued for this order
    email TEXT,
    created_at REAL NOT NULL
);
-- Web-push subscriptions: one row per browser/device endpoint. The endpoint is
-- the identity; a user can have several (phone + laptop).
CREATE TABLE IF NOT EXISTS push_subs (
    endpoint TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    created_at REAL NOT NULL
);
-- Direct messages between FRIENDS (profile-to-profile, outside any room).
CREATE TABLE IF NOT EXISTS dms (
    id TEXT PRIMARY KEY,
    from_user TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    to_user TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    created_at REAL NOT NULL,
    read INTEGER NOT NULL DEFAULT 0
);
-- Voice memos sent in DMs (blob in the db, like avatars). Referenced from
-- dms.voice_id; fetched via an unguessable capability URL.
CREATE TABLE IF NOT EXISTS dm_voice (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mime TEXT NOT NULL,
    data BLOB NOT NULL,
    created_at REAL NOT NULL
);
-- Tiny key-value store for server config that must survive restarts without
-- env changes (e.g. auto-generated VAPID keys on the persistent volume).
CREATE TABLE IF NOT EXISTS meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
-- Dagronde: the letter of each day, stored once so it is stable and so the
-- next day can be chosen to differ from it (no two days in a row the same).
CREATE TABLE IF NOT EXISTS daily_letters (
    day TEXT PRIMARY KEY,
    letter TEXT NOT NULL
);
-- Dagronde: first start per account per day (anchors the 60s submit window;
-- restarting the screen never resets it, so peeking costs your own clock).
CREATE TABLE IF NOT EXISTS daily_starts (
    day TEXT NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    started_at REAL NOT NULL,
    PRIMARY KEY (day, user_id)
);
-- Clubs: a friend group with its own leaderboard. One club per user (enforced
-- in code). The owner is a member too; ownership transfers to the oldest
-- remaining member when the owner leaves, or the club is deleted if empty.
CREATE TABLE IF NOT EXISTS clubs (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS club_members (
    club_id TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at REAL NOT NULL,
    PRIMARY KEY (club_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_club_members_user ON club_members(user_id);
-- Level-reward buzzer skins: which milestone skins a player has CLAIMED (the
-- victory-popup acknowledgement). A skin is USABLE once the level is reached;
-- this table only records the claim so the popup shows exactly once.
CREATE TABLE IF NOT EXISTS level_rewards (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reward TEXT NOT NULL,
    claimed_at REAL NOT NULL,
    PRIMARY KEY (user_id, reward)
);
-- Dagelijkse missies: progress per account per day per mission key. Rewards
-- auto-claim on completion (users.bonus_xp), so there is no claimed column.
CREATE TABLE IF NOT EXISTS mission_progress (
    day TEXT NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    progress INTEGER NOT NULL DEFAULT 0,
    done INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (day, user_id, key)
);
-- Dagronde: one ranked entry per account per day. words = the submitted
-- answers as JSON, kept so the player can re-open their result later.
CREATE TABLE IF NOT EXISTS daily_scores (
    day TEXT NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    time_ms INTEGER NOT NULL,
    words TEXT NOT NULL,
    created_at REAL NOT NULL,
    PRIMARY KEY (day, user_id)
);
CREATE INDEX IF NOT EXISTS idx_game_players_user ON game_players(user_id);
CREATE INDEX IF NOT EXISTS idx_games_finished ON games(finished_at);
CREATE INDEX IF NOT EXISTS idx_invites_to ON invites(to_user, status);
CREATE INDEX IF NOT EXISTS idx_ai_codes_open ON ai_codes(redeemed_by);
CREATE INDEX IF NOT EXISTS idx_push_user ON push_subs(user_id);
CREATE INDEX IF NOT EXISTS idx_dms_to ON dms(to_user, read);
CREATE INDEX IF NOT EXISTS idx_dms_pair ON dms(from_user, to_user, created_at);
"""


def _hash(secret: str) -> str:
    return hashlib.sha256(secret.encode()).hexdigest()


def _new_id() -> str:
    return secrets.token_hex(12)


# ---- preset avatars ---------------------------------------------------------
# 18 illustrated avatars (JPEG, gradient background baked in) shipped with the
# server. Picking one — or the default assigned at signup — stores its bytes as
# the account's avatar photo, so display works everywhere with zero extra
# plumbing. The frontend mirrors the same files under /avatars for the picker.
import pathlib as _pathlib

_AVATAR_DIR = _pathlib.Path(__file__).parent / "avatars"
PRESET_IDS = [f"av{i:02d}" for i in range(1, 19)]
# Premium pack (shop unlock, users.premium_avatars): av19..av36. Never part of
# the free defaults; picking one requires the unlock (set_avatar_preset gates).
PREMIUM_PRESET_IDS = [f"av{i:02d}" for i in range(19, 37)]
ALL_PRESET_IDS = PRESET_IDS + PREMIUM_PRESET_IDS

# Buzzer skins (shop 'buzzers' pack): art in frontend/public/buzzers/bzNN.webp.
# The default red buzzer is not an id here; NULL buzzer_skin = default.
BUZZER_SKIN_IDS = [f"bz{i:02d}" for i in range(1, 6)]  # the paid pack (bz01..05)
# Level-reward buzzer skins: (level threshold, skin id, name key for i18n).
# Reached by LEVELLING UP, never bought. Ordered by level.
LEVEL_BUZZERS = [
    (10, "bz06", "buzzReward_gold"),
    (20, "bz07", "buzzReward_diamond"),
    (30, "bz08", "buzzReward_royal"),
    (40, "bz09", "buzzReward_celestial"),
    (50, "bz10", "buzzReward_obsidian"),
    (75, "bz11", "buzzReward_prismatic"),
    (100, "bz12", "buzzReward_eternal"),
]
LEVEL_BUZZER_IDS = [b[1] for b in LEVEL_BUZZERS]
LEVEL_FOR_BUZZER = {skin: lvl for lvl, skin, _ in LEVEL_BUZZERS}
ALL_BUZZER_IDS = BUZZER_SKIN_IDS + LEVEL_BUZZER_IDS
_preset_cache: dict[str, Optional[bytes]] = {}


def preset_bytes(preset_id: str) -> Optional[bytes]:
    if preset_id not in ALL_PRESET_IDS:
        return None
    if preset_id not in _preset_cache:
        try:
            _preset_cache[preset_id] = (_AVATAR_DIR / f"{preset_id}.jpg").read_bytes()
        except Exception:
            _preset_cache[preset_id] = None
    return _preset_cache[preset_id]


def default_preset_for(user_id: str) -> str:
    """Stable, evenly-spread default preset for a user (no RNG, restart-safe)."""
    return PRESET_IDS[int(_hash(user_id), 16) % len(PRESET_IDS)]


class Database:
    def __init__(self, path: str = DB_PATH) -> None:
        self._lock = threading.Lock()
        self._conn = sqlite3.connect(path, check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        with self._lock:
            self._conn.executescript(
                "PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;" + _SCHEMA
            )
            self._conn.commit()
            self._migrate()

    def _migrate(self) -> None:
        """Additive migrations for DBs created before a column existed.
        CREATE TABLE IF NOT EXISTS never alters an existing table, so a prod DB
        keeps its old shape until we ADD COLUMN here."""
        cols = {r["name"] for r in self._conn.execute("PRAGMA table_info(users)").fetchall()}
        if "ai_unlocked" not in cols:
            self._conn.execute("ALTER TABLE users ADD COLUMN ai_unlocked INTEGER NOT NULL DEFAULT 0")
            self._conn.commit()
        if "avatar_preset" not in cols:
            self._conn.execute("ALTER TABLE users ADD COLUMN avatar_preset TEXT")
            self._conn.commit()
        # Mission rewards: bonus XP on top of the stats-derived XP (missions
        # auto-claim into this; _xp_of adds it to the level computation).
        if "bonus_xp" not in cols:
            self._conn.execute("ALTER TABLE users ADD COLUMN bonus_xp INTEGER NOT NULL DEFAULT 0")
            self._conn.commit()
        # Per-account soepele spelling: forgives near-miss spellings in Oefenen
        # and the Dagronde (a dyslexia aid), the same fuzzy match the room option
        # uses.
        if "lenient_spelling" not in cols:
            self._conn.execute("ALTER TABLE users ADD COLUMN lenient_spelling INTEGER NOT NULL DEFAULT 0")
            self._conn.commit()
        # Dagronde: remember which lenient setting a submission was scored with,
        # so re-opening the result stays consistent with the stored score.
        dcols = {r["name"] for r in self._conn.execute("PRAGMA table_info(daily_scores)").fetchall()}
        if dcols and "lenient" not in dcols:
            self._conn.execute("ALTER TABLE daily_scores ADD COLUMN lenient INTEGER NOT NULL DEFAULT 0")
            self._conn.commit()
        # Voice memos in DMs: reference + duration on the message row.
        mcols = {r["name"] for r in self._conn.execute("PRAGMA table_info(dms)").fetchall()}
        if mcols and "voice_id" not in mcols:
            self._conn.execute("ALTER TABLE dms ADD COLUMN voice_id TEXT")
            self._conn.execute("ALTER TABLE dms ADD COLUMN voice_dur INTEGER NOT NULL DEFAULT 0")
            self._conn.commit()
        # Chosen cosmetic title key (NULL -> show the auto rank label).
        if "title" not in cols:
            self._conn.execute("ALTER TABLE users ADD COLUMN title TEXT")
            self._conn.commit()
        # Premium avatar pack (av19..av36) bought in the shop.
        if "premium_avatars" not in cols:
            self._conn.execute("ALTER TABLE users ADD COLUMN premium_avatars INTEGER NOT NULL DEFAULT 0")
            self._conn.commit()
        # Shop is now multi-product: a code/order unlocks either 'ai' or
        # 'avatars'. Old rows predate the pack, so they default to 'ai'.
        accols = {r["name"] for r in self._conn.execute("PRAGMA table_info(ai_codes)").fetchall()}
        if "product" not in accols:
            self._conn.execute("ALTER TABLE ai_codes ADD COLUMN product TEXT NOT NULL DEFAULT 'ai'")
            self._conn.commit()
        pcols = {r["name"] for r in self._conn.execute("PRAGMA table_info(purchases)").fetchall()}
        if "product" not in pcols:
            self._conn.execute("ALTER TABLE purchases ADD COLUMN product TEXT NOT NULL DEFAULT 'ai'")
            self._conn.commit()
        # Buzzer skins: the pack unlock + the chosen skin (NULL = default red).
        if "buzzer_skins" not in cols:
            self._conn.execute("ALTER TABLE users ADD COLUMN buzzer_skins INTEGER NOT NULL DEFAULT 0")
            self._conn.execute("ALTER TABLE users ADD COLUMN buzzer_skin TEXT")
            self._conn.commit()
        # Preset artwork changed (v9 = the v8 body-width algorithm plus hand-tuned
        # per-avatar overrides, from per-avatar user feedback: av02 less zoom so
        # her shoulders are back, av06/13/14 nudged down, av15 down + recentered,
        # av16 pirate smaller with hat headroom, av17 cat a touch smaller, av18
        # alien smaller and fully in frame): refresh every account's preset
        # bytes, once per version.
        PRESET_ART_VERSION = "9"
        row = self._conn.execute("SELECT value FROM meta WHERE key='preset_art_version'").fetchone()
        if (row["value"] if row else None) != PRESET_ART_VERSION:
            for pid in PRESET_IDS:
                data = preset_bytes(pid)
                if data:
                    self._conn.execute(
                        "UPDATE users SET avatar=?, avatar_mime='image/jpeg', avatar_ver=avatar_ver+1 WHERE avatar_preset=?",
                        (data, pid),
                    )
            self._conn.execute(
                "INSERT OR REPLACE INTO meta (key, value) VALUES ('preset_art_version', ?)",
                (PRESET_ART_VERSION,),
            )
            self._conn.commit()

    def _exec(self, sql: str, args: tuple = ()) -> sqlite3.Cursor:
        cur = self._conn.execute(sql, args)
        self._conn.commit()
        return cur

    def _q(self, sql: str, args: tuple = ()) -> list[sqlite3.Row]:
        return self._conn.execute(sql, args).fetchall()

    # ---- users / auth -------------------------------------------------------

    @staticmethod
    def valid_name(name: str) -> bool:
        n = (name or "").strip()
        if not NAME_RE.match(n):
            return False
        low = n.lower()
        return not any(bad in low for bad in NAME_BLOCKLIST)

    def create_user(self, name: str, color: str) -> Optional[dict]:
        """Create an account + first device token. None if the name is taken/bad."""
        name = (name or "").strip()
        if not self.valid_name(name):
            return None
        uid = _new_id()
        token = secrets.token_hex(TOKEN_BYTES)
        now = time.time()
        with self._lock:
            try:
                self._exec(
                    "INSERT INTO users (id, name, name_lower, color, created_at) VALUES (?,?,?,?,?)",
                    (uid, name, name.lower(), color, now),
                )
            except sqlite3.IntegrityError:
                return None  # name taken
            self._exec(
                "INSERT INTO tokens (token_hash, user_id, created_at, last_seen) VALUES (?,?,?,?)",
                (_hash(token), uid, now, now),
            )
            # Everyone starts with a default illustrated avatar (changeable).
            pid = default_preset_for(uid)
            data = preset_bytes(pid)
            if data:
                self._exec(
                    "UPDATE users SET avatar=?, avatar_mime='image/jpeg', avatar_preset=? WHERE id=?",
                    (data, pid, uid),
                )
        return {"user_id": uid, "token": token, "name": name}

    def auth(self, token: str) -> Optional[str]:
        """token -> user_id (updates last_seen)."""
        if not token:
            return None
        with self._lock:
            rows = self._q("SELECT user_id FROM tokens WHERE token_hash=?", (_hash(token),))
            if not rows:
                return None
            self._exec("UPDATE tokens SET last_seen=? WHERE token_hash=?", (time.time(), _hash(token)))
            return rows[0]["user_id"]

    def get_user(self, user_id: str) -> Optional[dict]:
        with self._lock:
            rows = self._q(
                "SELECT id, name, email, color, avatar_ver, avatar IS NOT NULL AS has_avatar, "
                "avatar_preset, ai_unlocked, premium_avatars, buzzer_skins, buzzer_skin, title, lenient_spelling, created_at "
                "FROM users WHERE id=?",
                (user_id,),
            )
        return dict(rows[0]) if rows else None

    def set_lenient(self, user_id: str, on: bool) -> None:
        self._exec("UPDATE users SET lenient_spelling=? WHERE id=?", (int(on), user_id))

    def lenient_of(self, user_id: str) -> bool:
        with self._lock:
            rows = self._q("SELECT lenient_spelling FROM users WHERE id=?", (user_id,))
        return bool(rows[0]["lenient_spelling"]) if rows else False

    def get_title(self, user_id: str) -> Optional[str]:
        with self._lock:
            rows = self._q("SELECT title FROM users WHERE id=?", (user_id,))
        return rows[0]["title"] if rows else None

    def set_title(self, user_id: str, title: Optional[str]) -> None:
        self._exec("UPDATE users SET title=? WHERE id=?", (title, user_id))

    def find_users(self, query: str, limit: int = 8) -> list[dict]:
        q = (query or "").strip().lower()
        if len(q) < 2:
            return []
        with self._lock:
            rows = self._q(
                "SELECT id, name, color, avatar_ver, avatar IS NOT NULL AS has_avatar "
                "FROM users WHERE name_lower LIKE ? ORDER BY name_lower LIMIT ?",
                (q + "%", limit),
            )
        return [dict(r) for r in rows]

    def rename_user(self, user_id: str, name: str) -> bool:
        name = (name or "").strip()
        if not self.valid_name(name):
            return False
        with self._lock:
            try:
                self._exec(
                    "UPDATE users SET name=?, name_lower=? WHERE id=?",
                    (name, name.lower(), user_id),
                )
                return True
            except sqlite3.IntegrityError:
                return False

    def set_color(self, user_id: str, color: str) -> None:
        if re.match(r"^#[0-9A-Fa-f]{6}$", color or ""):
            with self._lock:
                self._exec("UPDATE users SET color=? WHERE id=?", (color, user_id))

    def delete_user(self, user_id: str) -> None:
        with self._lock:
            self._exec("DELETE FROM users WHERE id=?", (user_id,))

    # ---- avatar -------------------------------------------------------------

    def set_avatar(self, user_id: str, data: bytes, mime: str) -> bool:
        if not data or len(data) > AVATAR_MAX_BYTES or mime not in ("image/jpeg", "image/png", "image/webp"):
            return False
        with self._lock:
            # A custom photo clears the preset marker (no longer a preset choice).
            self._exec(
                "UPDATE users SET avatar=?, avatar_mime=?, avatar_preset=NULL, avatar_ver=avatar_ver+1 WHERE id=?",
                (data, mime, user_id),
            )
        return True

    def set_avatar_preset(self, user_id: str, preset_id: str) -> bool:
        """Store a built-in preset avatar as this account's photo. Premium pack
        presets (av19..av36) require the shop unlock; without it, refused."""
        data = preset_bytes(preset_id)
        if not data:
            return False
        if preset_id in PREMIUM_PRESET_IDS and not self.is_premium_avatars_unlocked(user_id):
            return False
        with self._lock:
            self._exec(
                "UPDATE users SET avatar=?, avatar_mime='image/jpeg', avatar_preset=?, avatar_ver=avatar_ver+1 WHERE id=?",
                (data, preset_id, user_id),
            )
        return True

    def ensure_avatar(self, user_id: str) -> Optional[str]:
        """Backfill: give an account without any avatar its default preset.
        Returns the assigned preset id, or None if it already had one."""
        with self._lock:
            rows = self._q("SELECT avatar IS NOT NULL AS has FROM users WHERE id=?", (user_id,))
            if not rows or rows[0]["has"]:
                return None
            pid = default_preset_for(user_id)
            data = preset_bytes(pid)
            if not data:
                return None
            self._exec(
                "UPDATE users SET avatar=?, avatar_mime='image/jpeg', avatar_preset=?, avatar_ver=avatar_ver+1 WHERE id=?",
                (data, pid, user_id),
            )
        return pid

    def clear_avatar(self, user_id: str) -> None:
        with self._lock:
            self._exec(
                "UPDATE users SET avatar=NULL, avatar_mime=NULL, avatar_preset=NULL, avatar_ver=avatar_ver+1 WHERE id=?",
                (user_id,),
            )

    def get_avatar(self, user_id: str) -> Optional[tuple[bytes, str]]:
        with self._lock:
            rows = self._q("SELECT avatar, avatar_mime FROM users WHERE id=?", (user_id,))
        if rows and rows[0]["avatar"]:
            return (rows[0]["avatar"], rows[0]["avatar_mime"] or "image/jpeg")
        return None

    # ---- email + magic link -------------------------------------------------

    def set_email(self, user_id: str, email: str) -> bool:
        email = (email or "").strip().lower()
        if not re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", email):
            return False
        with self._lock:
            try:
                self._exec("UPDATE users SET email=? WHERE id=?", (email, user_id))
                return True
            except sqlite3.IntegrityError:
                return False  # e-mail already linked to another account

    def start_login(self, email: str) -> Optional[tuple[str, str]]:
        """Request a magic-link code for the account behind this email.
        Returns (user_id, plain_code) or None if the email is unknown."""
        email = (email or "").strip().lower()
        with self._lock:
            rows = self._q("SELECT id FROM users WHERE email=?", (email,))
            if not rows:
                return None
            code = secrets.token_urlsafe(24)
            self._exec(
                "INSERT INTO login_codes (code_hash, user_id, expires_at) VALUES (?,?,?)",
                (_hash(code), rows[0]["id"], time.time() + LOGIN_CODE_TTL),
            )
            return (rows[0]["id"], code)

    def finish_login(self, code: str) -> Optional[dict]:
        """Redeem a one-time magic-link code -> fresh device token."""
        with self._lock:
            rows = self._q(
                "SELECT user_id FROM login_codes WHERE code_hash=? AND used=0 AND expires_at>?",
                (_hash(code), time.time()),
            )
            if not rows:
                return None
            uid = rows[0]["user_id"]
            self._exec("UPDATE login_codes SET used=1 WHERE code_hash=?", (_hash(code),))
            token = secrets.token_hex(TOKEN_BYTES)
            now = time.time()
            self._exec(
                "INSERT INTO tokens (token_hash, user_id, created_at, last_seen) VALUES (?,?,?,?)",
                (_hash(token), uid, now, now),
            )
            return {"user_id": uid, "token": token}

    # ---- friends / blocks ---------------------------------------------------

    @staticmethod
    def _pair(u1: str, u2: str) -> tuple[str, str]:
        return (u1, u2) if u1 < u2 else (u2, u1)

    def is_blocked(self, u1: str, u2: str) -> bool:
        with self._lock:
            rows = self._q(
                "SELECT 1 FROM blocks WHERE (user_id=? AND blocked_id=?) OR (user_id=? AND blocked_id=?)",
                (u1, u2, u2, u1),
            )
        return bool(rows)

    def friend_request(self, from_id: str, to_id: str) -> str:
        """Returns: 'sent' | 'accepted' (they had already asked you) | 'exists' | 'blocked' | 'invalid'."""
        if from_id == to_id or not self.get_user(to_id):
            return "invalid"
        if self.is_blocked(from_id, to_id):
            return "blocked"
        a, b = self._pair(from_id, to_id)
        with self._lock:
            rows = self._q("SELECT status, requested_by FROM friends WHERE a=? AND b=?", (a, b))
            if rows:
                if rows[0]["status"] == "accepted":
                    return "exists"
                if rows[0]["requested_by"] != from_id:
                    # They asked first: this request accepts it.
                    self._exec("UPDATE friends SET status='accepted' WHERE a=? AND b=?", (a, b))
                    return "accepted"
                return "exists"  # duplicate pending request
            self._exec(
                "INSERT INTO friends (a, b, status, requested_by, created_at) VALUES (?,?,?,?,?)",
                (a, b, "pending", from_id, time.time()),
            )
            return "sent"

    def friend_respond(self, user_id: str, other_id: str, accept: bool) -> bool:
        a, b = self._pair(user_id, other_id)
        with self._lock:
            rows = self._q(
                "SELECT 1 FROM friends WHERE a=? AND b=? AND status='pending' AND requested_by=?",
                (a, b, other_id),
            )
            if not rows:
                return False
            if accept:
                self._exec("UPDATE friends SET status='accepted' WHERE a=? AND b=?", (a, b))
            else:
                self._exec("DELETE FROM friends WHERE a=? AND b=?", (a, b))
            return True

    def friend_remove(self, user_id: str, other_id: str) -> None:
        a, b = self._pair(user_id, other_id)
        with self._lock:
            self._exec("DELETE FROM friends WHERE a=? AND b=?", (a, b))

    def block(self, user_id: str, other_id: str) -> None:
        self.friend_remove(user_id, other_id)
        with self._lock:
            self._exec(
                "INSERT OR IGNORE INTO blocks (user_id, blocked_id, created_at) VALUES (?,?,?)",
                (user_id, other_id, time.time()),
            )

    def unblock(self, user_id: str, other_id: str) -> None:
        with self._lock:
            self._exec("DELETE FROM blocks WHERE user_id=? AND blocked_id=?", (user_id, other_id))

    def blocked_of(self, user_id: str) -> list[dict]:
        """Users this user has blocked."""
        with self._lock:
            rows = self._q(
                """
                SELECT u.id, u.name, u.color, u.avatar_ver, u.avatar IS NOT NULL AS has_avatar
                FROM blocks b JOIN users u ON u.id = b.blocked_id
                WHERE b.user_id=? ORDER BY u.name_lower
                """,
                (user_id,),
            )
        return [dict(r) for r in rows]

    def friends_of(self, user_id: str) -> list[dict]:
        """Accepted friends + pending requests (both directions)."""
        with self._lock:
            rows = self._q(
                """
                SELECT u.id, u.name, u.color, u.avatar_ver, u.avatar IS NOT NULL AS has_avatar,
                       f.status, f.requested_by
                FROM friends f
                JOIN users u ON u.id = CASE WHEN f.a=? THEN f.b ELSE f.a END
                WHERE f.a=? OR f.b=?
                ORDER BY f.status, u.name_lower
                """,
                (user_id, user_id, user_id),
            )
        return [dict(r) for r in rows]

    # ---- invites ------------------------------------------------------------

    def create_invite(self, from_user: str, to_user: str, room_code: str, kind: str) -> Optional[dict]:
        if self.is_blocked(from_user, to_user):
            return None
        iid = _new_id()
        now = time.time()
        with self._lock:
            # One live invite per sender/receiver/room; refresh instead of stacking.
            self._exec(
                "DELETE FROM invites WHERE from_user=? AND to_user=? AND room_code=? AND status='pending'",
                (from_user, to_user, room_code),
            )
            self._exec(
                "INSERT INTO invites (id, from_user, to_user, room_code, kind, created_at) VALUES (?,?,?,?,?,?)",
                (iid, from_user, to_user, room_code, kind, now),
            )
        return {"id": iid, "from_user": from_user, "to_user": to_user, "room_code": room_code, "kind": kind, "created_at": now}

    def inbox(self, user_id: str) -> list[dict]:
        """Pending invites for this user (fresh ones only) + pending friend requests."""
        cutoff = time.time() - INVITE_TTL
        with self._lock:
            self._exec("DELETE FROM invites WHERE status='pending' AND created_at<?", (cutoff,))
            inv = self._q(
                """
                SELECT i.id, i.room_code, i.kind, i.created_at,
                       u.id AS from_id, u.name AS from_name, u.color AS from_color,
                       u.avatar_ver, u.avatar IS NOT NULL AS has_avatar
                FROM invites i JOIN users u ON u.id=i.from_user
                WHERE i.to_user=? AND i.status='pending'
                ORDER BY i.created_at DESC
                """,
                (user_id,),
            )
            reqs = self._q(
                """
                SELECT u.id AS from_id, u.name AS from_name, u.color AS from_color,
                       u.avatar_ver, u.avatar IS NOT NULL AS has_avatar, f.created_at
                FROM friends f
                JOIN users u ON u.id = f.requested_by
                WHERE (f.a=? OR f.b=?) AND f.status='pending' AND f.requested_by<>?
                ORDER BY f.created_at DESC
                """,
                (user_id, user_id, user_id),
            )
        items = [{**dict(r), "type": r["kind"]} for r in inv]
        items += [{**dict(r), "type": "friend_request"} for r in reqs]
        items.sort(key=lambda x: -x["created_at"])
        return items

    def resolve_invite(self, user_id: str, invite_id: str, accept: bool) -> Optional[str]:
        """Mark an invite handled. Returns the room code on accept."""
        with self._lock:
            rows = self._q(
                "SELECT room_code FROM invites WHERE id=? AND to_user=? AND status='pending'",
                (invite_id, user_id),
            )
            if not rows:
                return None
            self._exec(
                "UPDATE invites SET status=? WHERE id=?",
                ("accepted" if accept else "declined", invite_id),
            )
            return rows[0]["room_code"] if accept else None

    # ---- games / stats / badges --------------------------------------------

    def record_game(
        self,
        room_code: str,
        rounds: int,
        lenient: bool,
        players: list[dict],  # {user_id, score, is_winner, uniques, dubbels}
    ) -> Optional[str]:
        """Store a finished game for the account players. None if no accounts."""
        players = [p for p in players if p.get("user_id")]
        if not players:
            return None
        gid = _new_id()
        with self._lock:
            self._exec(
                "INSERT INTO games (id, room_code, finished_at, rounds, lenient) VALUES (?,?,?,?,?)",
                (gid, room_code, time.time(), rounds, int(lenient)),
            )
            for p in players:
                self._exec(
                    "INSERT OR REPLACE INTO game_players (game_id, user_id, score, is_winner, uniques, dubbels) "
                    "VALUES (?,?,?,?,?,?)",
                    (gid, p["user_id"], p["score"], int(p["is_winner"]), p.get("uniques", 0), p.get("dubbels", 0)),
                )
        return gid

    def stats_of(self, user_id: str) -> dict:
        with self._lock:
            rows = self._q(
                """
                SELECT COUNT(*) AS games, COALESCE(SUM(is_winner),0) AS wins,
                       COALESCE(SUM(score),0) AS points, COALESCE(MAX(score),0) AS best,
                       COALESCE(SUM(uniques),0) AS uniques, COALESCE(SUM(dubbels),0) AS dubbels
                FROM game_players WHERE user_id=?
                """,
                (user_id,),
            )
            streak_rows = self._q(
                """
                SELECT gp.is_winner FROM game_players gp
                JOIN games g ON g.id=gp.game_id
                WHERE gp.user_id=? ORDER BY g.finished_at DESC LIMIT 25
                """,
                (user_id,),
            )
        streak = 0
        for r in streak_rows:
            if r["is_winner"]:
                streak += 1
            else:
                break
        out = dict(rows[0])
        out["streak"] = streak
        with self._lock:
            bonus = self._q("SELECT bonus_xp FROM users WHERE id=?", (user_id,))
        out["bonus_xp"] = int(bonus[0]["bonus_xp"]) if bonus else 0
        return out

    # ---- dagelijkse missies ----------------------------------------------------

    def mission_bump(self, user_id: str, day: str, key: str, inc: int, target: int, reward: int) -> bool:
        """Add progress to a mission; True exactly when THIS bump completes it
        (the reward lands on users.bonus_xp right here, auto-claim)."""
        if inc <= 0:
            return False
        with self._lock:
            self._exec(
                "INSERT OR IGNORE INTO mission_progress (day, user_id, key, progress, done) VALUES (?,?,?,0,0)",
                (day, user_id, key),
            )
            row = self._q(
                "SELECT progress, done FROM mission_progress WHERE day=? AND user_id=? AND key=?",
                (day, user_id, key),
            )[0]
            if row["done"]:
                return False
            prog = min(target, int(row["progress"]) + inc)
            done = 1 if prog >= target else 0
            self._exec(
                "UPDATE mission_progress SET progress=?, done=? WHERE day=? AND user_id=? AND key=?",
                (prog, done, day, user_id, key),
            )
            if done:
                self._exec("UPDATE users SET bonus_xp = bonus_xp + ? WHERE id=?", (reward, user_id))
        return bool(done)

    def mission_state(self, user_id: str, day: str) -> dict:
        with self._lock:
            rows = self._q(
                "SELECT key, progress, done FROM mission_progress WHERE day=? AND user_id=?",
                (day, user_id),
            )
        return {r["key"]: {"progress": int(r["progress"]), "done": bool(r["done"])} for r in rows}

    # ---- clubs ---------------------------------------------------------------

    CLUB_MAX = 50

    def club_of(self, user_id: str) -> Optional[dict]:
        """The user's club (one per user) with owner flag + member count, or None."""
        with self._lock:
            rows = self._q(
                """
                SELECT c.id, c.name, c.code, c.owner_id,
                       (SELECT COUNT(*) FROM club_members m WHERE m.club_id=c.id) AS member_count
                FROM club_members cm JOIN clubs c ON c.id = cm.club_id
                WHERE cm.user_id = ? LIMIT 1
                """,
                (user_id,),
            )
        if not rows:
            return None
        r = dict(rows[0])
        return {"id": r["id"], "name": r["name"], "code": r["code"], "member_count": int(r["member_count"]), "is_owner": r["owner_id"] == user_id}

    def _gen_club_code(self) -> str:
        alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"  # no ambiguous chars
        while True:
            code = "".join(secrets.choice(alphabet) for _ in range(6))
            if not self._q("SELECT 1 FROM clubs WHERE code=?", (code,)):
                return code

    def create_club(self, owner_id: str, name: str) -> Optional[dict]:
        """Create a club with the owner as first member. None if the name is
        invalid or the user is already in a club."""
        name = (name or "").strip()[:24]
        if len(name) < 2 or self.club_of(owner_id) is not None:
            return None
        cid = _new_id()
        now = time.time()
        with self._lock:
            code = self._gen_club_code()
            self._exec("INSERT INTO clubs (id, name, code, owner_id, created_at) VALUES (?,?,?,?,?)", (cid, name, code, owner_id, now))
            self._exec("INSERT INTO club_members (club_id, user_id, joined_at) VALUES (?,?,?)", (cid, owner_id, now))
        return self.club_of(owner_id)

    def join_club(self, user_id: str, code: str) -> tuple[Optional[dict], str]:
        """Join by code. Returns (club, "") on success, else (None, reason_key)."""
        code = (code or "").strip().upper()
        if self.club_of(user_id) is not None:
            return None, "already_in_club"
        with self._lock:
            rows = self._q("SELECT id FROM clubs WHERE code=?", (code,))
            if not rows:
                return None, "no_club"
            cid = rows[0]["id"]
            n = self._q("SELECT COUNT(*) AS n FROM club_members WHERE club_id=?", (cid,))[0]["n"]
            if int(n) >= self.CLUB_MAX:
                return None, "club_full"
            self._exec("INSERT OR IGNORE INTO club_members (club_id, user_id, joined_at) VALUES (?,?,?)", (cid, user_id, time.time()))
        return self.club_of(user_id), ""

    def leave_club(self, user_id: str) -> None:
        """Leave your club. If you were the owner, pass it to the oldest
        remaining member; if none remain, delete the club."""
        club = self.club_of(user_id)
        if club is None:
            return
        cid = club["id"]
        with self._lock:
            self._exec("DELETE FROM club_members WHERE club_id=? AND user_id=?", (cid, user_id))
            if club["is_owner"]:
                rows = self._q("SELECT user_id FROM club_members WHERE club_id=? ORDER BY joined_at ASC LIMIT 1", (cid,))
                if rows:
                    self._exec("UPDATE clubs SET owner_id=? WHERE id=?", (rows[0]["user_id"], cid))
                else:
                    self._exec("DELETE FROM clubs WHERE id=?", (cid,))

    def club_ranked(self, club_id: str, since: float = 0.0, until: Optional[float] = None) -> list[dict]:
        """Members ranked by points over a period (members with no games in the
        window still appear, at 0). Bot games are never recorded, so they can't
        show up here."""
        with self._lock:
            members = self._q("SELECT user_id FROM club_members WHERE club_id=?", (club_id,))
            ids = [m["user_id"] for m in members]
            if not ids:
                return []
            owner = self._q("SELECT owner_id FROM clubs WHERE id=?", (club_id,))
            owner_id = owner[0]["owner_id"] if owner else None
            ph = ",".join("?" for _ in ids)
            rows = self._q(
                f"""
                SELECT u.id, u.name, u.color, u.avatar_ver, u.avatar IS NOT NULL AS has_avatar,
                       COALESCE(SUM(gp.score),0) AS points, COUNT(gp.game_id) AS games,
                       COALESCE(SUM(gp.is_winner),0) AS wins
                FROM users u
                LEFT JOIN game_players gp ON gp.user_id = u.id
                LEFT JOIN games g ON g.id = gp.game_id AND g.finished_at >= ? AND g.finished_at < ?
                WHERE u.id IN ({ph})
                GROUP BY u.id ORDER BY points DESC, wins DESC, u.name ASC
                """,
                (since, until if until is not None else float("inf"), *ids),
            )
        out = []
        for r in rows:
            d = dict(r)
            d["is_owner"] = d["id"] == owner_id
            out.append(d)
        return out

    def leaderboard(self, since: float = 0.0, until: Optional[float] = None, limit: int = 25) -> list[dict]:
        with self._lock:
            rows = self._q(
                """
                SELECT u.id, u.name, u.color, u.avatar_ver, u.avatar IS NOT NULL AS has_avatar,
                       COALESCE(SUM(gp.score),0) AS points, COUNT(*) AS games,
                       COALESCE(SUM(gp.is_winner),0) AS wins
                FROM game_players gp
                JOIN games g ON g.id=gp.game_id
                JOIN users u ON u.id=gp.user_id
                WHERE g.finished_at >= ? AND g.finished_at < ?
                GROUP BY u.id ORDER BY points DESC, wins DESC LIMIT ?
                """,
                (since, until if until is not None else float("inf"), limit),
            )
        return [dict(r) for r in rows]

    # ---- dagronde ------------------------------------------------------------

    def daily_letter_get(self, day: str) -> Optional[str]:
        with self._lock:
            rows = self._q("SELECT letter FROM daily_letters WHERE day=?", (day,))
        return rows[0]["letter"] if rows else None

    def daily_letter_set(self, day: str, letter: str) -> str:
        """Store the day's letter once; returns whatever ends up stored (so a
        concurrent writer never diverges — the pick is deterministic anyway)."""
        with self._lock:
            self._exec("INSERT OR IGNORE INTO daily_letters (day, letter) VALUES (?,?)", (day, letter))
            rows = self._q("SELECT letter FROM daily_letters WHERE day=?", (day,))
        return rows[0]["letter"] if rows else letter

    def daily_start(self, user_id: str, day: str, now: float) -> float:
        """Record the FIRST start of the day; later calls return that anchor."""
        with self._lock:
            row = self._q("SELECT started_at FROM daily_starts WHERE day=? AND user_id=?", (day, user_id))
            if row:
                return float(row[0]["started_at"])
            self._exec("INSERT INTO daily_starts (day, user_id, started_at) VALUES (?,?,?)", (day, user_id, now))
            return now

    def daily_submit(self, user_id: str, day: str, score: int, time_ms: int, words_json: str, now: float, lenient: bool = False) -> bool:
        """Store the day's entry. False if this account already played today."""
        with self._lock:
            try:
                self._exec(
                    "INSERT INTO daily_scores (day, user_id, score, time_ms, words, created_at, lenient) VALUES (?,?,?,?,?,?,?)",
                    (day, user_id, score, time_ms, words_json, now, int(lenient)),
                )
                return True
            except sqlite3.IntegrityError:
                return False

    def daily_entry(self, user_id: str, day: str) -> Optional[dict]:
        with self._lock:
            rows = self._q("SELECT score, time_ms, words, created_at, lenient FROM daily_scores WHERE day=? AND user_id=?", (day, user_id))
        return dict(rows[0]) if rows else None

    def daily_board(self, day: str, limit: int = 25) -> list[dict]:
        with self._lock:
            rows = self._q(
                """
                SELECT u.id, u.name, u.color, u.avatar_ver, u.avatar IS NOT NULL AS has_avatar,
                       ds.score, ds.time_ms
                FROM daily_scores ds JOIN users u ON u.id = ds.user_id
                WHERE ds.day = ?
                ORDER BY ds.score DESC, ds.time_ms ASC, ds.created_at ASC
                LIMIT ?
                """,
                (day, limit),
            )
        return [dict(r) for r in rows]

    def daily_rank(self, user_id: str, day: str) -> tuple[int, int]:
        """(rank, total players) for the day; rank 0 when not on the board."""
        with self._lock:
            total = self._q("SELECT COUNT(*) AS n FROM daily_scores WHERE day=?", (day,))[0]["n"]
            mine = self._q("SELECT score, time_ms, created_at FROM daily_scores WHERE day=? AND user_id=?", (day, user_id))
            if not mine:
                return 0, int(total)
            m = mine[0]
            better = self._q(
                """
                SELECT COUNT(*) AS n FROM daily_scores WHERE day=? AND (
                    score > ? OR (score = ? AND time_ms < ?) OR
                    (score = ? AND time_ms = ? AND created_at < ?)
                )
                """,
                (day, m["score"], m["score"], m["time_ms"], m["score"], m["time_ms"], m["created_at"]),
            )[0]["n"]
        return int(better) + 1, int(total)

    def daily_days_of(self, user_id: str, limit: int = 400) -> list[str]:
        """The days this account played, newest first (streak computation)."""
        with self._lock:
            rows = self._q("SELECT day FROM daily_scores WHERE user_id=? ORDER BY day DESC LIMIT ?", (user_id, limit))
        return [r["day"] for r in rows]

    def daily_players_count(self, day: str) -> int:
        with self._lock:
            return int(self._q("SELECT COUNT(*) AS n FROM daily_scores WHERE day=?", (day,))[0]["n"])

    def history_of(self, user_id: str, limit: int = 10) -> list[dict]:
        """The user's most recent games, newest first, each with their own
        score/place and the co-players (name/color/avatar + score)."""
        with self._lock:
            games = self._q(
                """
                SELECT g.id, g.finished_at, g.rounds, gp.score, gp.is_winner
                FROM game_players gp JOIN games g ON g.id = gp.game_id
                WHERE gp.user_id = ? ORDER BY g.finished_at DESC LIMIT ?
                """,
                (user_id, limit),
            )
            out = []
            for g in games:
                rows = self._q(
                    """
                    SELECT gp.user_id, gp.score, u.name, u.color, u.avatar_ver,
                           u.avatar IS NOT NULL AS has_avatar
                    FROM game_players gp JOIN users u ON u.id = gp.user_id
                    WHERE gp.game_id = ? ORDER BY gp.score DESC
                    """,
                    (g["id"],),
                )
                players = [dict(r) for r in rows]
                place = next((i + 1 for i, r in enumerate(players) if r["user_id"] == user_id), 0)
                out.append({
                    "finished_at": g["finished_at"],
                    "rounds": g["rounds"],
                    "score": g["score"],
                    "is_winner": bool(g["is_winner"]),
                    "place": place,
                    "player_count": len(players),
                    "players": players,
                })
        return out

    def head_to_head(self, u1: str, u2: str) -> dict:
        """Shared games between two users: how often they played together and
        who won how many of those games."""
        with self._lock:
            rows = self._q(
                """
                SELECT a.is_winner AS w1, b.is_winner AS w2
                FROM game_players a
                JOIN game_players b ON b.game_id = a.game_id AND b.user_id = ?
                WHERE a.user_id = ?
                """,
                (u2, u1),
            )
        return {
            "games": len(rows),
            "my_wins": sum(1 for r in rows if r["w1"]),
            "their_wins": sum(1 for r in rows if r["w2"]),
        }

    def grant_badge(self, user_id: str, badge: str) -> bool:
        """True if newly earned."""
        with self._lock:
            cur = self._exec(
                "INSERT OR IGNORE INTO badges (user_id, badge, earned_at) VALUES (?,?,?)",
                (user_id, badge, time.time()),
            )
            return cur.rowcount > 0

    def badges_of(self, user_id: str) -> list[dict]:
        with self._lock:
            rows = self._q(
                "SELECT badge, earned_at FROM badges WHERE user_id=? ORDER BY earned_at",
                (user_id,),
            )
        return [dict(r) for r in rows]

    # ---- meta (key-value, e.g. auto-generated VAPID keys) --------------------

    def meta_get(self, key: str) -> Optional[str]:
        with self._lock:
            rows = self._q("SELECT value FROM meta WHERE key=?", (key,))
        return rows[0]["value"] if rows else None

    def meta_set(self, key: str, value: str) -> None:
        with self._lock:
            self._exec("INSERT OR REPLACE INTO meta (key, value) VALUES (?,?)", (key, value))

    # ---- web-push subscriptions ----------------------------------------------

    def push_subscribe(self, user_id: str, endpoint: str, p256dh: str, auth: str) -> bool:
        if not (user_id and endpoint and p256dh and auth):
            return False
        with self._lock:
            self._exec(
                "INSERT OR REPLACE INTO push_subs (endpoint, user_id, p256dh, auth, created_at) VALUES (?,?,?,?,?)",
                (endpoint, user_id, p256dh, auth, time.time()),
            )
        return True

    def push_unsubscribe(self, endpoint: str) -> None:
        with self._lock:
            self._exec("DELETE FROM push_subs WHERE endpoint=?", (endpoint,))

    def push_subs_of(self, user_id: str) -> list[dict]:
        with self._lock:
            rows = self._q("SELECT endpoint, p256dh, auth FROM push_subs WHERE user_id=?", (user_id,))
        return [dict(r) for r in rows]

    # ---- direct messages (friends only; gate checked by the caller) ----------

    DM_MAX_LEN = 500

    def dm_voice_store(self, user_id: str, mime: str, data: bytes) -> str:
        """Store a DM voice memo blob; keep a per-user cap so storage stays sane."""
        vid = _new_id()
        with self._lock:
            self._exec(
                "INSERT INTO dm_voice (id, user_id, mime, data, created_at) VALUES (?,?,?,?,?)",
                (vid, user_id, mime, data, time.time()),
            )
            self._exec(
                "DELETE FROM dm_voice WHERE user_id=? AND id NOT IN "
                "(SELECT id FROM dm_voice WHERE user_id=? ORDER BY created_at DESC LIMIT 200)",
                (user_id, user_id),
            )
        return vid

    def dm_voice_get(self, vid: str) -> Optional[tuple[str, bytes]]:
        with self._lock:
            row = self._q("SELECT mime, data FROM dm_voice WHERE id=?", (vid,))
        if not row:
            return None
        return row[0]["mime"], row[0]["data"]

    def dm_send(self, from_user: str, to_user: str, text: str,
                voice_id: Optional[str] = None, voice_dur: int = 0) -> Optional[dict]:
        text = (text or "").strip()[: self.DM_MAX_LEN]
        if voice_id:
            # The memo must be the sender's own upload; a voice message has no text.
            with self._lock:
                owned = self._q("SELECT 1 FROM dm_voice WHERE id=? AND user_id=?", (voice_id, from_user))
            if not owned:
                return None
            text = ""
            voice_dur = max(0, min(120, int(voice_dur or 0)))
        elif not text:
            return None
        if from_user == to_user:
            return None
        mid = _new_id()
        now = time.time()
        with self._lock:
            self._exec(
                "INSERT INTO dms (id, from_user, to_user, text, created_at, voice_id, voice_dur) VALUES (?,?,?,?,?,?,?)",
                (mid, from_user, to_user, text, now, voice_id, voice_dur if voice_id else 0),
            )
        return {"id": mid, "from_user": from_user, "to_user": to_user, "text": text,
                "created_at": now, "voice_id": voice_id, "voice_dur": voice_dur if voice_id else 0}

    def dm_thread(self, user_id: str, other_id: str, limit: int = 60) -> list[dict]:
        """Conversation between two users, oldest first. Marks the incoming
        half as read."""
        with self._lock:
            rows = self._q(
                "SELECT id, from_user, to_user, text, created_at, voice_id, voice_dur FROM dms "
                "WHERE (from_user=? AND to_user=?) OR (from_user=? AND to_user=?) "
                "ORDER BY created_at DESC LIMIT ?",
                (user_id, other_id, other_id, user_id, limit),
            )
            self._exec("UPDATE dms SET read=1 WHERE from_user=? AND to_user=? AND read=0", (other_id, user_id))
        return [dict(r) for r in reversed(rows)]

    def dm_threads(self, user_id: str) -> list[dict]:
        """One row per conversation partner: partner id, last message, unread
        count. Newest conversation first."""
        with self._lock:
            rows = self._q(
                """
                SELECT CASE WHEN from_user=? THEN to_user ELSE from_user END AS partner,
                       MAX(created_at) AS last_at
                FROM dms WHERE from_user=? OR to_user=?
                GROUP BY partner ORDER BY last_at DESC LIMIT 30
                """,
                (user_id, user_id, user_id),
            )
            out = []
            for r in rows:
                last = self._q(
                    "SELECT from_user, text, created_at, voice_id FROM dms "
                    "WHERE (from_user=? AND to_user=?) OR (from_user=? AND to_user=?) "
                    "ORDER BY created_at DESC LIMIT 1",
                    (user_id, r["partner"], r["partner"], user_id),
                )[0]
                unread = self._q(
                    "SELECT COUNT(*) AS n FROM dms WHERE from_user=? AND to_user=? AND read=0",
                    (r["partner"], user_id),
                )[0]["n"]
                out.append({
                    "partner": r["partner"],
                    "last_text": last["text"],
                    "last_voice": bool(last["voice_id"]),
                    "last_from_me": last["from_user"] == user_id,
                    "last_at": last["created_at"],
                    "unread": unread,
                })
        return out

    def dm_unread_total(self, user_id: str) -> int:
        with self._lock:
            rows = self._q("SELECT COUNT(*) AS n FROM dms WHERE to_user=? AND read=0", (user_id,))
        return rows[0]["n"]

    def is_friend(self, u1: str, u2: str) -> bool:
        a, b = self._pair(u1, u2)
        with self._lock:
            rows = self._q("SELECT 1 FROM friends WHERE a=? AND b=? AND status='accepted'", (a, b))
        return bool(rows)

    # ---- shop: AI-referee unlock codes --------------------------------------

    def is_ai_unlocked(self, user_id: str) -> bool:
        if not user_id:
            return False
        with self._lock:
            rows = self._q("SELECT ai_unlocked FROM users WHERE id=?", (user_id,))
        return bool(rows and rows[0]["ai_unlocked"])

    def is_premium_avatars_unlocked(self, user_id: str) -> bool:
        if not user_id:
            return False
        with self._lock:
            rows = self._q("SELECT premium_avatars FROM users WHERE id=?", (user_id,))
        return bool(rows and rows[0]["premium_avatars"])

    def is_buzzers_unlocked(self, user_id: str) -> bool:
        if not user_id:
            return False
        with self._lock:
            rows = self._q("SELECT buzzer_skins FROM users WHERE id=?", (user_id,))
        return bool(rows and rows[0]["buzzer_skins"])

    def set_buzzer_skin(self, user_id: str, skin: Optional[str], allowed: set) -> bool:
        """Pick a buzzer skin the caller has verified is allowed (pack ownership
        for bz01..05, level reached for the reward skins), or None to go back to
        the default red buzzer (always allowed)."""
        if not skin:
            self._exec("UPDATE users SET buzzer_skin=NULL WHERE id=?", (user_id,))
            return True
        if skin not in allowed:
            return False
        self._exec("UPDATE users SET buzzer_skin=? WHERE id=?", (skin, user_id))
        return True

    # ---- level-reward buzzer skins (unlocked by levelling up) --------------

    def level_rewards_claimed(self, user_id: str) -> set:
        with self._lock:
            rows = self._q("SELECT reward FROM level_rewards WHERE user_id=?", (user_id,))
        return {r["reward"] for r in rows}

    def claim_level_reward(self, user_id: str, reward: str) -> None:
        self._exec(
            "INSERT OR IGNORE INTO level_rewards (user_id, reward, claimed_at) VALUES (?,?,?)",
            (user_id, reward, time.time()),
        )

    def _new_ai_code(self) -> str:
        # Human-friendly, unambiguous alphabet (no O/0/I/1), grouped for reading.
        alpha = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
        return "-".join("".join(secrets.choice(alpha) for _ in range(4)) for _ in range(3))

    # Which users column a product unlocks.
    _PRODUCT_COL = {"ai": "ai_unlocked", "avatars": "premium_avatars", "buzzers": "buzzer_skins"}

    def create_ai_code(self, source: str = "admin", product: str = "ai") -> str:
        """Mint a fresh unlock code for `product`, store only its hash, return
        the plain code."""
        product = product if product in self._PRODUCT_COL else "ai"
        with self._lock:
            while True:
                code = self._new_ai_code()
                h = _hash(code)
                exists = self._q("SELECT 1 FROM ai_codes WHERE code_hash=?", (h,))
                if exists:
                    continue
                self._exec(
                    "INSERT INTO ai_codes (code_hash, source, product, created_at) VALUES (?,?,?,?)",
                    (h, source if source in ("admin", "paypal") else "admin", product, time.time()),
                )
                return code

    def redeem_ai_code(self, user_id: str, code: str) -> str:
        """Redeem an unlock code for this account. The code carries which product
        it unlocks (ai | avatars | buzzers). Returns:
        'ok' | 'already' (account already had this product) | 'used' | 'invalid'."""
        code = (code or "").strip().upper().replace(" ", "")
        if not code or not user_id:
            return "invalid"
        h = _hash(code)
        with self._lock:  # non-reentrant lock: query inline, never call get_user()
            urows = self._q("SELECT ai_unlocked, premium_avatars, buzzer_skins FROM users WHERE id=?", (user_id,))
            if not urows:
                return "invalid"
            rows = self._q("SELECT redeemed_by, product FROM ai_codes WHERE code_hash=?", (h,))
            if not rows:
                return "invalid"
            product = rows[0]["product"] or "ai"
            col = self._PRODUCT_COL.get(product, "ai_unlocked")
            if urows[0][col]:
                return "already"
            if rows[0]["redeemed_by"]:
                return "used"
            self._exec(
                "UPDATE ai_codes SET redeemed_by=?, redeemed_at=? WHERE code_hash=? AND redeemed_by IS NULL",
                (user_id, time.time(), h),
            )
            self._exec(f"UPDATE users SET {col}=1 WHERE id=?", (user_id,))
        return "ok"

    def ai_code_stats(self, product: str = "ai") -> dict:
        product = product if product in self._PRODUCT_COL else "ai"
        with self._lock:
            rows = self._q(
                "SELECT COUNT(*) AS total, COALESCE(SUM(redeemed_by IS NOT NULL),0) AS redeemed "
                "FROM ai_codes WHERE product=?",
                (product,),
            )
        r = rows[0]
        return {"total": r["total"], "redeemed": r["redeemed"], "open": r["total"] - r["redeemed"]}

    def get_user_by_token(self, token: str) -> Optional[dict]:
        uid = self.auth(token)
        return self.get_user(uid) if uid else None

    # ---- shop: PayPal purchases (idempotent by order id) --------------------

    def purchase_code(self, order_id: str) -> Optional[str]:
        """The code already issued for this PayPal order, if any (idempotency)."""
        if not order_id:
            return None
        with self._lock:
            rows = self._q("SELECT code FROM purchases WHERE order_id=?", (order_id,))
        return rows[0]["code"] if rows else None

    def fulfil_purchase(
        self, order_id: str, user_id: str, amount: str, currency: str,
        email: Optional[str] = None, product: str = "ai",
    ) -> Optional[str]:
        """Record a captured PayPal order and unlock `product` for the buyer,
        exactly once. Returns the issued unlock code, or None if this order was
        already fulfilled by a concurrent request (caller reads purchase_code())."""
        if not order_id or not user_id:
            return None
        product = product if product in self._PRODUCT_COL else "ai"
        col = self._PRODUCT_COL[product]
        code = self._new_ai_code()
        now = time.time()
        with self._lock:
            # INSERT OR IGNORE on the order id is the idempotency gate: a replayed
            # capture hits the existing row and inserts nothing.
            cur = self._exec(
                "INSERT OR IGNORE INTO purchases (order_id, provider, product, user_id, amount, currency, code, email, created_at) "
                "VALUES (?,?,?,?,?,?,?,?,?)",
                (order_id, "paypal", product, user_id, amount, currency, code, email, now),
            )
            if cur.rowcount == 0:
                return None  # already fulfilled; caller reads purchase_code()
            self._exec(
                "INSERT OR IGNORE INTO ai_codes (code_hash, source, product, created_at, redeemed_by, redeemed_at) VALUES (?,?,?,?,?,?)",
                (_hash(code), "paypal", product, now, user_id, now),
            )
            self._exec(f"UPDATE users SET {col}=1 WHERE id=?", (user_id,))
        return code


# Module-level singleton, created lazily so tests can use their own path.
_db: Optional[Database] = None


def get_db() -> Database:
    global _db
    if _db is None:
        _db = Database()
    return _db
