"""Pen Neer — persistence layer (SQLite, stdlib sqlite3).

Everything account-related lives here: users, device tokens, magic-link login
codes, friendships, blocks, room invites, game history and badges. Rooms stay
in-memory (RoomManager); this database only holds what must survive a restart.

Single-process server, tiny queries: sync sqlite3 behind one lock is plenty.
WAL mode keeps readers and the writer out of each other's way. The DB path
comes from PENNEER_DB_PATH (prod: a Coolify persistent volume, e.g.
/data/penneer.db) and falls back to ./penneer.db for local dev.
"""
from __future__ import annotations

import hashlib
import os
import re
import secrets
import sqlite3
import threading
import time
from typing import Any, Optional

DB_PATH = os.environ.get("PENNEER_DB_PATH", "penneer.db")

NAME_RE = re.compile(r"^[A-Za-z0-9À-ÿ_\- ]{2,20}$")
# Small blunt blocklist for public profile names (substring match, lowercase).
NAME_BLOCKLIST = ("hitler", "nazi", "kanker", "neger", "faggot")

TOKEN_BYTES = 24
LOGIN_CODE_TTL = 15 * 60          # magic link valid for 15 minutes
INVITE_TTL = 60 * 60              # room invites expire after an hour
AVATAR_MAX_BYTES = 300_000        # client resizes to ~256px JPEG; hard cap here

_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    name_lower TEXT NOT NULL UNIQUE,
    email TEXT UNIQUE,
    avatar BLOB,
    avatar_mime TEXT,
    avatar_ver INTEGER NOT NULL DEFAULT 0,
    color TEXT NOT NULL DEFAULT '#FFC23D',
    ai_unlocked INTEGER NOT NULL DEFAULT 0,   -- AI referee bought for this account
    created_at REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS tokens (
    token_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at REAL NOT NULL,
    last_seen REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS login_codes (
    code_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at REAL NOT NULL,
    used INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS friends (
    a TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    b TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status TEXT NOT NULL,             -- pending | accepted
    requested_by TEXT NOT NULL,
    created_at REAL NOT NULL,
    PRIMARY KEY (a, b)                -- canonical: a < b
);
CREATE TABLE IF NOT EXISTS blocks (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at REAL NOT NULL,
    PRIMARY KEY (user_id, blocked_id)
);
CREATE TABLE IF NOT EXISTS invites (
    id TEXT PRIMARY KEY,
    from_user TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    to_user TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    room_code TEXT NOT NULL,
    kind TEXT NOT NULL,               -- invite | challenge
    status TEXT NOT NULL DEFAULT 'pending',  -- pending | accepted | declined
    created_at REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS games (
    id TEXT PRIMARY KEY,
    room_code TEXT NOT NULL,
    finished_at REAL NOT NULL,
    rounds INTEGER NOT NULL,
    lenient INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS game_players (
    game_id TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    is_winner INTEGER NOT NULL,
    uniques INTEGER NOT NULL DEFAULT 0,
    dubbels INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (game_id, user_id)
);
CREATE TABLE IF NOT EXISTS badges (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    badge TEXT NOT NULL,
    earned_at REAL NOT NULL,
    PRIMARY KEY (user_id, badge)
);
-- Shop: one-time codes that unlock the AI referee for ONE account (never admin).
-- Generated by the owner (source 'admin') or minted on a paid PayPal order
-- (source 'paypal'). Only the hash is stored; the plain code is shown once.
CREATE TABLE IF NOT EXISTS ai_codes (
    code_hash TEXT PRIMARY KEY,
    source TEXT NOT NULL,              -- admin | paypal
    created_at REAL NOT NULL,
    redeemed_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    redeemed_at REAL
);
-- PayPal purchases, keyed by the PayPal order id so a capture is idempotent
-- (a ret/replayed capture returns the same already-issued code, never a second).
CREATE TABLE IF NOT EXISTS purchases (
    order_id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    user_id TEXT,
    amount TEXT,
    currency TEXT,
    code TEXT,                         -- the ai_code plain value issued for this order
    email TEXT,
    created_at REAL NOT NULL
);
-- Web-push subscriptions: one row per browser/device endpoint. The endpoint is
-- the identity; a user can have several (phone + laptop).
CREATE TABLE IF NOT EXISTS push_subs (
    endpoint TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    created_at REAL NOT NULL
);
-- Direct messages between FRIENDS (profile-to-profile, outside any room).
CREATE TABLE IF NOT EXISTS dms (
    id TEXT PRIMARY KEY,
    from_user TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    to_user TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    created_at REAL NOT NULL,
    read INTEGER NOT NULL DEFAULT 0
);
-- Tiny key-value store for server config that must survive restarts without
-- env changes (e.g. auto-generated VAPID keys on the persistent volume).
CREATE TABLE IF NOT EXISTS meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_game_players_user ON game_players(user_id);
CREATE INDEX IF NOT EXISTS idx_games_finished ON games(finished_at);
CREATE INDEX IF NOT EXISTS idx_invites_to ON invites(to_user, status);
CREATE INDEX IF NOT EXISTS idx_ai_codes_open ON ai_codes(redeemed_by);
CREATE INDEX IF NOT EXISTS idx_push_user ON push_subs(user_id);
CREATE INDEX IF NOT EXISTS idx_dms_to ON dms(to_user, read);
CREATE INDEX IF NOT EXISTS idx_dms_pair ON dms(from_user, to_user, created_at);
"""


def _hash(secret: str) -> str:
    return hashlib.sha256(secret.encode()).hexdigest()


def _new_id() -> str:
    return secrets.token_hex(12)


# ---- preset avatars ---------------------------------------------------------
# 18 illustrated avatars (JPEG, gradient background baked in) shipped with the
# server. Picking one — or the default assigned at signup — stores its bytes as
# the account's avatar photo, so display works everywhere with zero extra
# plumbing. The frontend mirrors the same files under /avatars for the picker.
import pathlib as _pathlib

_AVATAR_DIR = _pathlib.Path(__file__).parent / "avatars"
PRESET_IDS = [f"av{i:02d}" for i in range(1, 19)]
_preset_cache: dict[str, Optional[bytes]] = {}


def preset_bytes(preset_id: str) -> Optional[bytes]:
    if preset_id not in PRESET_IDS:
        return None
    if preset_id not in _preset_cache:
        try:
            _preset_cache[preset_id] = (_AVATAR_DIR / f"{preset_id}.jpg").read_bytes()
        except Exception:
            _preset_cache[preset_id] = None
    return _preset_cache[preset_id]


def default_preset_for(user_id: str) -> str:
    """Stable, evenly-spread default preset for a user (no RNG, restart-safe)."""
    return PRESET_IDS[int(_hash(user_id), 16) % len(PRESET_IDS)]


class Database:
    def __init__(self, path: str = DB_PATH) -> None:
        self._lock = threading.Lock()
        self._conn = sqlite3.connect(path, check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        with self._lock:
            self._conn.executescript(
                "PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;" + _SCHEMA
            )
            self._conn.commit()
            self._migrate()

    def _migrate(self) -> None:
        """Additive migrations for DBs created before a column existed.
        CREATE TABLE IF NOT EXISTS never alters an existing table, so a prod DB
        keeps its old shape until we ADD COLUMN here."""
        cols = {r["name"] for r in self._conn.execute("PRAGMA table_info(users)").fetchall()}
        if "ai_unlocked" not in cols:
            self._conn.execute("ALTER TABLE users ADD COLUMN ai_unlocked INTEGER NOT NULL DEFAULT 0")
            self._conn.commit()
        if "avatar_preset" not in cols:
            self._conn.execute("ALTER TABLE users ADD COLUMN avatar_preset TEXT")
            self._conn.commit()

    def _exec(self, sql: str, args: tuple = ()) -> sqlite3.Cursor:
        cur = self._conn.execute(sql, args)
        self._conn.commit()
        return cur

    def _q(self, sql: str, args: tuple = ()) -> list[sqlite3.Row]:
        return self._conn.execute(sql, args).fetchall()

    # ---- users / auth -------------------------------------------------------

    @staticmethod
    def valid_name(name: str) -> bool:
        n = (name or "").strip()
        if not NAME_RE.match(n):
            return False
        low = n.lower()
        return not any(bad in low for bad in NAME_BLOCKLIST)

    def create_user(self, name: str, color: str) -> Optional[dict]:
        """Create an account + first device token. None if the name is taken/bad."""
        name = (name or "").strip()
        if not self.valid_name(name):
            return None
        uid = _new_id()
        token = secrets.token_hex(TOKEN_BYTES)
        now = time.time()
        with self._lock:
            try:
                self._exec(
                    "INSERT INTO users (id, name, name_lower, color, created_at) VALUES (?,?,?,?,?)",
                    (uid, name, name.lower(), color, now),
                )
            except sqlite3.IntegrityError:
                return None  # name taken
            self._exec(
                "INSERT INTO tokens (token_hash, user_id, created_at, last_seen) VALUES (?,?,?,?)",
                (_hash(token), uid, now, now),
            )
            # Everyone starts with a default illustrated avatar (changeable).
            pid = default_preset_for(uid)
            data = preset_bytes(pid)
            if data:
                self._exec(
                    "UPDATE users SET avatar=?, avatar_mime='image/jpeg', avatar_preset=? WHERE id=?",
                    (data, pid, uid),
                )
        return {"user_id": uid, "token": token, "name": name}

    def auth(self, token: str) -> Optional[str]:
        """token -> user_id (updates last_seen)."""
        if not token:
            return None
        with self._lock:
            rows = self._q("SELECT user_id FROM tokens WHERE token_hash=?", (_hash(token),))
            if not rows:
                return None
            self._exec("UPDATE tokens SET last_seen=? WHERE token_hash=?", (time.time(), _hash(token)))
            return rows[0]["user_id"]

    def get_user(self, user_id: str) -> Optional[dict]:
        with self._lock:
            rows = self._q(
                "SELECT id, name, email, color, avatar_ver, avatar IS NOT NULL AS has_avatar, "
                "avatar_preset, ai_unlocked, created_at "
                "FROM users WHERE id=?",
                (user_id,),
            )
        return dict(rows[0]) if rows else None

    def find_users(self, query: str, limit: int = 8) -> list[dict]:
        q = (query or "").strip().lower()
        if len(q) < 2:
            return []
        with self._lock:
            rows = self._q(
                "SELECT id, name, color, avatar_ver, avatar IS NOT NULL AS has_avatar "
                "FROM users WHERE name_lower LIKE ? ORDER BY name_lower LIMIT ?",
                (q + "%", limit),
            )
        return [dict(r) for r in rows]

    def rename_user(self, user_id: str, name: str) -> bool:
        name = (name or "").strip()
        if not self.valid_name(name):
            return False
        with self._lock:
            try:
                self._exec(
                    "UPDATE users SET name=?, name_lower=? WHERE id=?",
                    (name, name.lower(), user_id),
                )
                return True
            except sqlite3.IntegrityError:
                return False

    def set_color(self, user_id: str, color: str) -> None:
        if re.match(r"^#[0-9A-Fa-f]{6}$", color or ""):
            with self._lock:
                self._exec("UPDATE users SET color=? WHERE id=?", (color, user_id))

    def delete_user(self, user_id: str) -> None:
        with self._lock:
            self._exec("DELETE FROM users WHERE id=?", (user_id,))

    # ---- avatar -------------------------------------------------------------

    def set_avatar(self, user_id: str, data: bytes, mime: str) -> bool:
        if not data or len(data) > AVATAR_MAX_BYTES or mime not in ("image/jpeg", "image/png", "image/webp"):
            return False
        with self._lock:
            # A custom photo clears the preset marker (no longer a preset choice).
            self._exec(
                "UPDATE users SET avatar=?, avatar_mime=?, avatar_preset=NULL, avatar_ver=avatar_ver+1 WHERE id=?",
                (data, mime, user_id),
            )
        return True

    def set_avatar_preset(self, user_id: str, preset_id: str) -> bool:
        """Store a built-in preset avatar as this account's photo."""
        data = preset_bytes(preset_id)
        if not data:
            return False
        with self._lock:
            self._exec(
                "UPDATE users SET avatar=?, avatar_mime='image/jpeg', avatar_preset=?, avatar_ver=avatar_ver+1 WHERE id=?",
                (data, preset_id, user_id),
            )
        return True

    def ensure_avatar(self, user_id: str) -> Optional[str]:
        """Backfill: give an account without any avatar its default preset.
        Returns the assigned preset id, or None if it already had one."""
        with self._lock:
            rows = self._q("SELECT avatar IS NOT NULL AS has FROM users WHERE id=?", (user_id,))
            if not rows or rows[0]["has"]:
                return None
            pid = default_preset_for(user_id)
            data = preset_bytes(pid)
            if not data:
                return None
            self._exec(
                "UPDATE users SET avatar=?, avatar_mime='image/jpeg', avatar_preset=?, avatar_ver=avatar_ver+1 WHERE id=?",
                (data, pid, user_id),
            )
        return pid

    def clear_avatar(self, user_id: str) -> None:
        with self._lock:
            self._exec(
                "UPDATE users SET avatar=NULL, avatar_mime=NULL, avatar_preset=NULL, avatar_ver=avatar_ver+1 WHERE id=?",
                (user_id,),
            )

    def get_avatar(self, user_id: str) -> Optional[tuple[bytes, str]]:
        with self._lock:
            rows = self._q("SELECT avatar, avatar_mime FROM users WHERE id=?", (user_id,))
        if rows and rows[0]["avatar"]:
            return (rows[0]["avatar"], rows[0]["avatar_mime"] or "image/jpeg")
        return None

    # ---- email + magic link -------------------------------------------------

    def set_email(self, user_id: str, email: str) -> bool:
        email = (email or "").strip().lower()
        if not re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", email):
            return False
        with self._lock:
            try:
                self._exec("UPDATE users SET email=? WHERE id=?", (email, user_id))
                return True
            except sqlite3.IntegrityError:
                return False  # e-mail already linked to another account

    def start_login(self, email: str) -> Optional[tuple[str, str]]:
        """Request a magic-link code for the account behind this email.
        Returns (user_id, plain_code) or None if the email is unknown."""
        email = (email or "").strip().lower()
        with self._lock:
            rows = self._q("SELECT id FROM users WHERE email=?", (email,))
            if not rows:
                return None
            code = secrets.token_urlsafe(24)
            self._exec(
                "INSERT INTO login_codes (code_hash, user_id, expires_at) VALUES (?,?,?)",
                (_hash(code), rows[0]["id"], time.time() + LOGIN_CODE_TTL),
            )
            return (rows[0]["id"], code)

    def finish_login(self, code: str) -> Optional[dict]:
        """Redeem a one-time magic-link code -> fresh device token."""
        with self._lock:
            rows = self._q(
                "SELECT user_id FROM login_codes WHERE code_hash=? AND used=0 AND expires_at>?",
                (_hash(code), time.time()),
            )
            if not rows:
                return None
            uid = rows[0]["user_id"]
            self._exec("UPDATE login_codes SET used=1 WHERE code_hash=?", (_hash(code),))
            token = secrets.token_hex(TOKEN_BYTES)
            now = time.time()
            self._exec(
                "INSERT INTO tokens (token_hash, user_id, created_at, last_seen) VALUES (?,?,?,?)",
                (_hash(token), uid, now, now),
            )
            return {"user_id": uid, "token": token}

    # ---- friends / blocks ---------------------------------------------------

    @staticmethod
    def _pair(u1: str, u2: str) -> tuple[str, str]:
        return (u1, u2) if u1 < u2 else (u2, u1)

    def is_blocked(self, u1: str, u2: str) -> bool:
        with self._lock:
            rows = self._q(
                "SELECT 1 FROM blocks WHERE (user_id=? AND blocked_id=?) OR (user_id=? AND blocked_id=?)",
                (u1, u2, u2, u1),
            )
        return bool(rows)

    def friend_request(self, from_id: str, to_id: str) -> str:
        """Returns: 'sent' | 'accepted' (they had already asked you) | 'exists' | 'blocked' | 'invalid'."""
        if from_id == to_id or not self.get_user(to_id):
            return "invalid"
        if self.is_blocked(from_id, to_id):
            return "blocked"
        a, b = self._pair(from_id, to_id)
        with self._lock:
            rows = self._q("SELECT status, requested_by FROM friends WHERE a=? AND b=?", (a, b))
            if rows:
                if rows[0]["status"] == "accepted":
                    return "exists"
                if rows[0]["requested_by"] != from_id:
                    # They asked first: this request accepts it.
                    self._exec("UPDATE friends SET status='accepted' WHERE a=? AND b=?", (a, b))
                    return "accepted"
                return "exists"  # duplicate pending request
            self._exec(
                "INSERT INTO friends (a, b, status, requested_by, created_at) VALUES (?,?,?,?,?)",
                (a, b, "pending", from_id, time.time()),
            )
            return "sent"

    def friend_respond(self, user_id: str, other_id: str, accept: bool) -> bool:
        a, b = self._pair(user_id, other_id)
        with self._lock:
            rows = self._q(
                "SELECT 1 FROM friends WHERE a=? AND b=? AND status='pending' AND requested_by=?",
                (a, b, other_id),
            )
            if not rows:
                return False
            if accept:
                self._exec("UPDATE friends SET status='accepted' WHERE a=? AND b=?", (a, b))
            else:
                self._exec("DELETE FROM friends WHERE a=? AND b=?", (a, b))
            return True

    def friend_remove(self, user_id: str, other_id: str) -> None:
        a, b = self._pair(user_id, other_id)
        with self._lock:
            self._exec("DELETE FROM friends WHERE a=? AND b=?", (a, b))

    def block(self, user_id: str, other_id: str) -> None:
        self.friend_remove(user_id, other_id)
        with self._lock:
            self._exec(
                "INSERT OR IGNORE INTO blocks (user_id, blocked_id, created_at) VALUES (?,?,?)",
                (user_id, other_id, time.time()),
            )

    def unblock(self, user_id: str, other_id: str) -> None:
        with self._lock:
            self._exec("DELETE FROM blocks WHERE user_id=? AND blocked_id=?", (user_id, other_id))

    def blocked_of(self, user_id: str) -> list[dict]:
        """Users this user has blocked."""
        with self._lock:
            rows = self._q(
                """
                SELECT u.id, u.name, u.color, u.avatar_ver, u.avatar IS NOT NULL AS has_avatar
                FROM blocks b JOIN users u ON u.id = b.blocked_id
                WHERE b.user_id=? ORDER BY u.name_lower
                """,
                (user_id,),
            )
        return [dict(r) for r in rows]

    def friends_of(self, user_id: str) -> list[dict]:
        """Accepted friends + pending requests (both directions)."""
        with self._lock:
            rows = self._q(
                """
                SELECT u.id, u.name, u.color, u.avatar_ver, u.avatar IS NOT NULL AS has_avatar,
                       f.status, f.requested_by
                FROM friends f
                JOIN users u ON u.id = CASE WHEN f.a=? THEN f.b ELSE f.a END
                WHERE f.a=? OR f.b=?
                ORDER BY f.status, u.name_lower
                """,
                (user_id, user_id, user_id),
            )
        return [dict(r) for r in rows]

    # ---- invites ------------------------------------------------------------

    def create_invite(self, from_user: str, to_user: str, room_code: str, kind: str) -> Optional[dict]:
        if self.is_blocked(from_user, to_user):
            return None
        iid = _new_id()
        now = time.time()
        with self._lock:
            # One live invite per sender/receiver/room; refresh instead of stacking.
            self._exec(
                "DELETE FROM invites WHERE from_user=? AND to_user=? AND room_code=? AND status='pending'",
                (from_user, to_user, room_code),
            )
            self._exec(
                "INSERT INTO invites (id, from_user, to_user, room_code, kind, created_at) VALUES (?,?,?,?,?,?)",
                (iid, from_user, to_user, room_code, kind, now),
            )
        return {"id": iid, "from_user": from_user, "to_user": to_user, "room_code": room_code, "kind": kind, "created_at": now}

    def inbox(self, user_id: str) -> list[dict]:
        """Pending invites for this user (fresh ones only) + pending friend requests."""
        cutoff = time.time() - INVITE_TTL
        with self._lock:
            self._exec("DELETE FROM invites WHERE status='pending' AND created_at<?", (cutoff,))
            inv = self._q(
                """
                SELECT i.id, i.room_code, i.kind, i.created_at,
                       u.id AS from_id, u.name AS from_name, u.color AS from_color,
                       u.avatar_ver, u.avatar IS NOT NULL AS has_avatar
                FROM invites i JOIN users u ON u.id=i.from_user
                WHERE i.to_user=? AND i.status='pending'
                ORDER BY i.created_at DESC
                """,
                (user_id,),
            )
            reqs = self._q(
                """
                SELECT u.id AS from_id, u.name AS from_name, u.color AS from_color,
                       u.avatar_ver, u.avatar IS NOT NULL AS has_avatar, f.created_at
                FROM friends f
                JOIN users u ON u.id = f.requested_by
                WHERE (f.a=? OR f.b=?) AND f.status='pending' AND f.requested_by<>?
                ORDER BY f.created_at DESC
                """,
                (user_id, user_id, user_id),
            )
        items = [{**dict(r), "type": r["kind"]} for r in inv]
        items += [{**dict(r), "type": "friend_request"} for r in reqs]
        items.sort(key=lambda x: -x["created_at"])
        return items

    def resolve_invite(self, user_id: str, invite_id: str, accept: bool) -> Optional[str]:
        """Mark an invite handled. Returns the room code on accept."""
        with self._lock:
            rows = self._q(
                "SELECT room_code FROM invites WHERE id=? AND to_user=? AND status='pending'",
                (invite_id, user_id),
            )
            if not rows:
                return None
            self._exec(
                "UPDATE invites SET status=? WHERE id=?",
                ("accepted" if accept else "declined", invite_id),
            )
            return rows[0]["room_code"] if accept else None

    # ---- games / stats / badges --------------------------------------------

    def record_game(
        self,
        room_code: str,
        rounds: int,
        lenient: bool,
        players: list[dict],  # {user_id, score, is_winner, uniques, dubbels}
    ) -> Optional[str]:
        """Store a finished game for the account players. None if no accounts."""
        players = [p for p in players if p.get("user_id")]
        if not players:
            return None
        gid = _new_id()
        with self._lock:
            self._exec(
                "INSERT INTO games (id, room_code, finished_at, rounds, lenient) VALUES (?,?,?,?,?)",
                (gid, room_code, time.time(), rounds, int(lenient)),
            )
            for p in players:
                self._exec(
                    "INSERT OR REPLACE INTO game_players (game_id, user_id, score, is_winner, uniques, dubbels) "
                    "VALUES (?,?,?,?,?,?)",
                    (gid, p["user_id"], p["score"], int(p["is_winner"]), p.get("uniques", 0), p.get("dubbels", 0)),
                )
        return gid

    def stats_of(self, user_id: str) -> dict:
        with self._lock:
            rows = self._q(
                """
                SELECT COUNT(*) AS games, COALESCE(SUM(is_winner),0) AS wins,
                       COALESCE(SUM(score),0) AS points, COALESCE(MAX(score),0) AS best,
                       COALESCE(SUM(uniques),0) AS uniques, COALESCE(SUM(dubbels),0) AS dubbels
                FROM game_players WHERE user_id=?
                """,
                (user_id,),
            )
            streak_rows = self._q(
                """
                SELECT gp.is_winner FROM game_players gp
                JOIN games g ON g.id=gp.game_id
                WHERE gp.user_id=? ORDER BY g.finished_at DESC LIMIT 25
                """,
                (user_id,),
            )
        streak = 0
        for r in streak_rows:
            if r["is_winner"]:
                streak += 1
            else:
                break
        out = dict(rows[0])
        out["streak"] = streak
        return out

    def leaderboard(self, since: float = 0.0, until: Optional[float] = None, limit: int = 25) -> list[dict]:
        with self._lock:
            rows = self._q(
                """
                SELECT u.id, u.name, u.color, u.avatar_ver, u.avatar IS NOT NULL AS has_avatar,
                       COALESCE(SUM(gp.score),0) AS points, COUNT(*) AS games,
                       COALESCE(SUM(gp.is_winner),0) AS wins
                FROM game_players gp
                JOIN games g ON g.id=gp.game_id
                JOIN users u ON u.id=gp.user_id
                WHERE g.finished_at >= ? AND g.finished_at < ?
                GROUP BY u.id ORDER BY points DESC, wins DESC LIMIT ?
                """,
                (since, until if until is not None else float("inf"), limit),
            )
        return [dict(r) for r in rows]

    def history_of(self, user_id: str, limit: int = 10) -> list[dict]:
        """The user's most recent games, newest first, each with their own
        score/place and the co-players (name/color/avatar + score)."""
        with self._lock:
            games = self._q(
                """
                SELECT g.id, g.finished_at, g.rounds, gp.score, gp.is_winner
                FROM game_players gp JOIN games g ON g.id = gp.game_id
                WHERE gp.user_id = ? ORDER BY g.finished_at DESC LIMIT ?
                """,
                (user_id, limit),
            )
            out = []
            for g in games:
                rows = self._q(
                    """
                    SELECT gp.user_id, gp.score, u.name, u.color, u.avatar_ver,
                           u.avatar IS NOT NULL AS has_avatar
                    FROM game_players gp JOIN users u ON u.id = gp.user_id
                    WHERE gp.game_id = ? ORDER BY gp.score DESC
                    """,
                    (g["id"],),
                )
                players = [dict(r) for r in rows]
                place = next((i + 1 for i, r in enumerate(players) if r["user_id"] == user_id), 0)
                out.append({
                    "finished_at": g["finished_at"],
                    "rounds": g["rounds"],
                    "score": g["score"],
                    "is_winner": bool(g["is_winner"]),
                    "place": place,
                    "player_count": len(players),
                    "players": players,
                })
        return out

    def head_to_head(self, u1: str, u2: str) -> dict:
        """Shared games between two users: how often they played together and
        who won how many of those games."""
        with self._lock:
            rows = self._q(
                """
                SELECT a.is_winner AS w1, b.is_winner AS w2
                FROM game_players a
                JOIN game_players b ON b.game_id = a.game_id AND b.user_id = ?
                WHERE a.user_id = ?
                """,
                (u2, u1),
            )
        return {
            "games": len(rows),
            "my_wins": sum(1 for r in rows if r["w1"]),
            "their_wins": sum(1 for r in rows if r["w2"]),
        }

    def grant_badge(self, user_id: str, badge: str) -> bool:
        """True if newly earned."""
        with self._lock:
            cur = self._exec(
                "INSERT OR IGNORE INTO badges (user_id, badge, earned_at) VALUES (?,?,?)",
                (user_id, badge, time.time()),
            )
            return cur.rowcount > 0

    def badges_of(self, user_id: str) -> list[dict]:
        with self._lock:
            rows = self._q(
                "SELECT badge, earned_at FROM badges WHERE user_id=? ORDER BY earned_at",
                (user_id,),
            )
        return [dict(r) for r in rows]

    # ---- meta (key-value, e.g. auto-generated VAPID keys) --------------------

    def meta_get(self, key: str) -> Optional[str]:
        with self._lock:
            rows = self._q("SELECT value FROM meta WHERE key=?", (key,))
        return rows[0]["value"] if rows else None

    def meta_set(self, key: str, value: str) -> None:
        with self._lock:
            self._exec("INSERT OR REPLACE INTO meta (key, value) VALUES (?,?)", (key, value))

    # ---- web-push subscriptions ----------------------------------------------

    def push_subscribe(self, user_id: str, endpoint: str, p256dh: str, auth: str) -> bool:
        if not (user_id and endpoint and p256dh and auth):
            return False
        with self._lock:
            self._exec(
                "INSERT OR REPLACE INTO push_subs (endpoint, user_id, p256dh, auth, created_at) VALUES (?,?,?,?,?)",
                (endpoint, user_id, p256dh, auth, time.time()),
            )
        return True

    def push_unsubscribe(self, endpoint: str) -> None:
        with self._lock:
            self._exec("DELETE FROM push_subs WHERE endpoint=?", (endpoint,))

    def push_subs_of(self, user_id: str) -> list[dict]:
        with self._lock:
            rows = self._q("SELECT endpoint, p256dh, auth FROM push_subs WHERE user_id=?", (user_id,))
        return [dict(r) for r in rows]

    # ---- direct messages (friends only; gate checked by the caller) ----------

    DM_MAX_LEN = 500

    def dm_send(self, from_user: str, to_user: str, text: str) -> Optional[dict]:
        text = (text or "").strip()[: self.DM_MAX_LEN]
        if not text or from_user == to_user:
            return None
        mid = _new_id()
        now = time.time()
        with self._lock:
            self._exec(
                "INSERT INTO dms (id, from_user, to_user, text, created_at) VALUES (?,?,?,?,?)",
                (mid, from_user, to_user, text, now),
            )
        return {"id": mid, "from_user": from_user, "to_user": to_user, "text": text, "created_at": now}

    def dm_thread(self, user_id: str, other_id: str, limit: int = 60) -> list[dict]:
        """Conversation between two users, oldest first. Marks the incoming
        half as read."""
        with self._lock:
            rows = self._q(
                "SELECT id, from_user, to_user, text, created_at FROM dms "
                "WHERE (from_user=? AND to_user=?) OR (from_user=? AND to_user=?) "
                "ORDER BY created_at DESC LIMIT ?",
                (user_id, other_id, other_id, user_id, limit),
            )
            self._exec("UPDATE dms SET read=1 WHERE from_user=? AND to_user=? AND read=0", (other_id, user_id))
        return [dict(r) for r in reversed(rows)]

    def dm_threads(self, user_id: str) -> list[dict]:
        """One row per conversation partner: partner id, last message, unread
        count. Newest conversation first."""
        with self._lock:
            rows = self._q(
                """
                SELECT CASE WHEN from_user=? THEN to_user ELSE from_user END AS partner,
                       MAX(created_at) AS last_at
                FROM dms WHERE from_user=? OR to_user=?
                GROUP BY partner ORDER BY last_at DESC LIMIT 30
                """,
                (user_id, user_id, user_id),
            )
            out = []
            for r in rows:
                last = self._q(
                    "SELECT from_user, text, created_at FROM dms "
                    "WHERE (from_user=? AND to_user=?) OR (from_user=? AND to_user=?) "
                    "ORDER BY created_at DESC LIMIT 1",
                    (user_id, r["partner"], r["partner"], user_id),
                )[0]
                unread = self._q(
                    "SELECT COUNT(*) AS n FROM dms WHERE from_user=? AND to_user=? AND read=0",
                    (r["partner"], user_id),
                )[0]["n"]
                out.append({
                    "partner": r["partner"],
                    "last_text": last["text"],
                    "last_from_me": last["from_user"] == user_id,
                    "last_at": last["created_at"],
                    "unread": unread,
                })
        return out

    def dm_unread_total(self, user_id: str) -> int:
        with self._lock:
            rows = self._q("SELECT COUNT(*) AS n FROM dms WHERE to_user=? AND read=0", (user_id,))
        return rows[0]["n"]

    def is_friend(self, u1: str, u2: str) -> bool:
        a, b = self._pair(u1, u2)
        with self._lock:
            rows = self._q("SELECT 1 FROM friends WHERE a=? AND b=? AND status='accepted'", (a, b))
        return bool(rows)

    # ---- shop: AI-referee unlock codes --------------------------------------

    def is_ai_unlocked(self, user_id: str) -> bool:
        if not user_id:
            return False
        with self._lock:
            rows = self._q("SELECT ai_unlocked FROM users WHERE id=?", (user_id,))
        return bool(rows and rows[0]["ai_unlocked"])

    def _new_ai_code(self) -> str:
        # Human-friendly, unambiguous alphabet (no O/0/I/1), grouped for reading.
        alpha = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
        return "-".join("".join(secrets.choice(alpha) for _ in range(4)) for _ in range(3))

    def create_ai_code(self, source: str = "admin") -> str:
        """Mint a fresh unlock code, store only its hash, return the plain code."""
        with self._lock:
            while True:
                code = self._new_ai_code()
                h = _hash(code)
                exists = self._q("SELECT 1 FROM ai_codes WHERE code_hash=?", (h,))
                if exists:
                    continue
                self._exec(
                    "INSERT INTO ai_codes (code_hash, source, created_at) VALUES (?,?,?)",
                    (h, source if source in ("admin", "paypal") else "admin", time.time()),
                )
                return code

    def redeem_ai_code(self, user_id: str, code: str) -> str:
        """Redeem an unlock code for this account. Returns:
        'ok' | 'already' (account already had AI) | 'used' | 'invalid'."""
        code = (code or "").strip().upper().replace(" ", "")
        if not code or not user_id:
            return "invalid"
        h = _hash(code)
        with self._lock:  # non-reentrant lock: query inline, never call get_user()
            urows = self._q("SELECT ai_unlocked FROM users WHERE id=?", (user_id,))
            if not urows:
                return "invalid"
            if urows[0]["ai_unlocked"]:
                return "already"
            rows = self._q("SELECT redeemed_by FROM ai_codes WHERE code_hash=?", (h,))
            if not rows:
                return "invalid"
            if rows[0]["redeemed_by"]:
                return "used"
            self._exec(
                "UPDATE ai_codes SET redeemed_by=?, redeemed_at=? WHERE code_hash=? AND redeemed_by IS NULL",
                (user_id, time.time(), h),
            )
            self._exec("UPDATE users SET ai_unlocked=1 WHERE id=?", (user_id,))
        return "ok"

    def ai_code_stats(self) -> dict:
        with self._lock:
            rows = self._q(
                "SELECT COUNT(*) AS total, COALESCE(SUM(redeemed_by IS NOT NULL),0) AS redeemed FROM ai_codes"
            )
        r = rows[0]
        return {"total": r["total"], "redeemed": r["redeemed"], "open": r["total"] - r["redeemed"]}

    def get_user_by_token(self, token: str) -> Optional[dict]:
        uid = self.auth(token)
        return self.get_user(uid) if uid else None

    # ---- shop: PayPal purchases (idempotent by order id) --------------------

    def purchase_code(self, order_id: str) -> Optional[str]:
        """The code already issued for this PayPal order, if any (idempotency)."""
        if not order_id:
            return None
        with self._lock:
            rows = self._q("SELECT code FROM purchases WHERE order_id=?", (order_id,))
        return rows[0]["code"] if rows else None

    def fulfil_purchase(
        self, order_id: str, user_id: str, amount: str, currency: str, email: Optional[str] = None
    ) -> Optional[str]:
        """Record a captured PayPal order and unlock the buyer's AI, exactly once.
        Returns the issued unlock code, or None if this order was already fulfilled
        by a concurrent request (the caller should then read purchase_code())."""
        if not order_id or not user_id:
            return None
        code = self._new_ai_code()
        now = time.time()
        with self._lock:
            # INSERT OR IGNORE on the order id is the idempotency gate: a replayed
            # capture hits the existing row and inserts nothing.
            cur = self._exec(
                "INSERT OR IGNORE INTO purchases (order_id, provider, user_id, amount, currency, code, email, created_at) "
                "VALUES (?,?,?,?,?,?,?,?)",
                (order_id, "paypal", user_id, amount, currency, code, email, now),
            )
            if cur.rowcount == 0:
                return None  # already fulfilled; caller reads purchase_code()
            self._exec(
                "INSERT OR IGNORE INTO ai_codes (code_hash, source, created_at, redeemed_by, redeemed_at) VALUES (?,?,?,?,?)",
                (_hash(code), "paypal", now, user_id, now),
            )
            self._exec("UPDATE users SET ai_unlocked=1 WHERE id=?", (user_id,))
        return code


# Module-level singleton, created lazily so tests can use their own path.
_db: Optional[Database] = None


def get_db() -> Database:
    global _db
    if _db is None:
        _db = Database()
    return _db
